In [3]:
from __future__ import print_function

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import cv2

from keras.models import Sequential

from keras.layers import Conv2D, MaxPooling2D, GlobalAveragePooling2D
from keras.layers import Dense

from keras.utils import plot_model
from keras.utils import np_utils

/Users/manishashivshette/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [4]:
raw_data = pd.read_csv('Multi-Label-Fashion-MNIST-master/labels.csv')

print(len(raw_data))


10000


In [5]:
raw_data.head()


index  fname                           label    real_int  \
0      0  0.png  [0, 1, 1, 0, 0, 0, 0, 0, 1, 0]  2, 8, 1, 8   
1      1  1.png  [0, 0, 0, 1, 0, 0, 0, 1, 0, 1]  9, 3, 7, 7   
2      2  2.png  [1, 1, 1, 0, 0, 0, 0, 0, 0, 0]  1, 0, 0, 2   
3      3  3.png  [0, 1, 0, 1, 0, 0, 0, 0, 0, 1]  3, 9, 3, 1   
4      4  4.png  [0, 0, 1, 0, 0, 1, 1, 1, 0, 0]  2, 5, 7, 6   

                                      real_str  
0                  Pullover, Bag, Trouser, Bag  
1          Ankle boot, Dress, Sneaker, Sneaker  
2  Trouser, T-shirt/top, T-shirt/top, Pullover  
3            Dress, Ankle boot, Dress, Trouser  
4             Pullover, Sandal, Sneaker, Shirt

In [6]:
raw_pic = []
raw_lbl = []

for i in range(0, len(raw_data)):
    item = raw_data.iloc[i]
    
    img_file = 'Multi-Label-Fashion-MNIST-master/' + item['fname']
    print(img_file)
    img = cv2.imread(img_file)

    y = 0
    h = 160
    x = 0
    w = 640 
    
    crop_img = img[y:y+h, x:x+w]
    crop_img = cv2.cvtColor(crop_img, cv2.COLOR_BGR2RGB)
    raw_pic.append(crop_img)
    
    lbl = item['label']
    print(lbl)
    lbl_in_np = np.fromstring(lbl[1:-1], dtype=int, sep=',')
    print(lbl_in_np)
    
    raw_lbl.append(lbl_in_np)

Multi-Label-Fashion-MNIST-master/0.png
[0, 1, 1, 0, 0, 0, 0, 0, 1, 0]
[0 1 1 0 0 0 0 0 1 0]
Multi-Label-Fashion-MNIST-master/1.png
[0, 0, 0, 1, 0, 0, 0, 1, 0, 1]
[0 0 0 1 0 0 0 1 0 1]
Multi-Label-Fashion-MNIST-master/2.png
[1, 1, 1, 0, 0, 0, 0, 0, 0, 0]
[1 1 1 0 0 0 0 0 0 0]
Multi-Label-Fashion-MNIST-master/3.png
[0, 1, 0, 1, 0, 0, 0, 0, 0, 1]
[0 1 0 1 0 0 0 0 0 1]
Multi-Label-Fashion-MNIST-master/4.png
[0, 0, 1, 0, 0, 1, 1, 1, 0, 0]
[0 0 1 0 0 1 1 1 0 0]
Multi-Label-Fashion-MNIST-master/5.png
[1, 1, 1, 0, 0, 0, 0, 0, 0, 0]
[1 1 1 0 0 0 0 0 0 0]
Multi-Label-Fashion-MNIST-master/6.png
[0, 1, 1, 0, 0, 1, 0, 0, 1, 0]
[0 1 1 0 0 1 0 0 1 0]
Multi-Label-Fashion-MNIST-master/7.png
[1, 1, 1, 0, 0, 1, 0, 0, 0, 0]
[1 1 1 0 0 1 0 0 0 0]
Multi-Label-Fashion-MNIST-master/8.png
[0, 0, 0, 1, 1, 1, 1, 0, 0, 0]
[0 0 0 1 1 1 1 0 0 0]
Multi-Label-Fashion-MNIST-master/9.png
[0, 0, 0, 1, 1, 1, 0, 0, 0, 0]
[0 0 0 1 1 1 0 0 0 0]
Multi-Label-Fashion-MNIST-master/10.png
[0, 0, 1, 1, 0, 1, 0, 0, 0, 1]
[0 0 1 1 

[0, 0, 0, 0, 0, 1, 1, 1, 1, 0]
[0 0 0 0 0 1 1 1 1 0]
Multi-Label-Fashion-MNIST-master/131.png
[0, 1, 0, 0, 0, 1, 0, 0, 1, 0]
[0 1 0 0 0 1 0 0 1 0]
Multi-Label-Fashion-MNIST-master/132.png
[0, 1, 1, 1, 0, 0, 1, 0, 0, 0]
[0 1 1 1 0 0 1 0 0 0]
Multi-Label-Fashion-MNIST-master/133.png
[0, 0, 1, 1, 1, 0, 0, 0, 1, 0]
[0 0 1 1 1 0 0 0 1 0]
Multi-Label-Fashion-MNIST-master/134.png
[0, 1, 1, 0, 1, 0, 0, 0, 1, 0]
[0 1 1 0 1 0 0 0 1 0]
Multi-Label-Fashion-MNIST-master/135.png
[0, 1, 1, 0, 0, 1, 0, 0, 0, 1]
[0 1 1 0 0 1 0 0 0 1]
Multi-Label-Fashion-MNIST-master/136.png
[1, 0, 0, 0, 0, 0, 0, 0, 1, 1]
[1 0 0 0 0 0 0 0 1 1]
Multi-Label-Fashion-MNIST-master/137.png
[0, 1, 1, 0, 0, 1, 0, 0, 1, 0]
[0 1 1 0 0 1 0 0 1 0]
Multi-Label-Fashion-MNIST-master/138.png
[0, 1, 0, 0, 0, 0, 1, 1, 1, 0]
[0 1 0 0 0 0 1 1 1 0]
Multi-Label-Fashion-MNIST-master/139.png
[0, 0, 1, 0, 0, 1, 1, 1, 0, 0]
[0 0 1 0 0 1 1 1 0 0]
Multi-Label-Fashion-MNIST-master/140.png
[1, 1, 0, 0, 0, 0, 0, 1, 1, 0]
[1 1 0 0 0 0 0 1 1 0]
Multi-L

[0, 0, 1, 0, 0, 0, 1, 0, 1, 0]
[0 0 1 0 0 0 1 0 1 0]
Multi-Label-Fashion-MNIST-master/266.png
[0, 0, 0, 0, 1, 0, 1, 1, 0, 0]
[0 0 0 0 1 0 1 1 0 0]
Multi-Label-Fashion-MNIST-master/267.png
[1, 0, 1, 0, 0, 0, 0, 0, 1, 0]
[1 0 1 0 0 0 0 0 1 0]
Multi-Label-Fashion-MNIST-master/268.png
[0, 0, 0, 1, 0, 1, 0, 1, 0, 0]
[0 0 0 1 0 1 0 1 0 0]
Multi-Label-Fashion-MNIST-master/269.png
[0, 0, 1, 0, 0, 0, 1, 0, 1, 0]
[0 0 1 0 0 0 1 0 1 0]
Multi-Label-Fashion-MNIST-master/270.png
[0, 0, 1, 0, 0, 0, 0, 1, 1, 1]
[0 0 1 0 0 0 0 1 1 1]
Multi-Label-Fashion-MNIST-master/271.png
[0, 0, 1, 0, 0, 0, 1, 0, 1, 1]
[0 0 1 0 0 0 1 0 1 1]
Multi-Label-Fashion-MNIST-master/272.png
[0, 0, 0, 0, 0, 0, 1, 0, 1, 1]
[0 0 0 0 0 0 1 0 1 1]
Multi-Label-Fashion-MNIST-master/273.png
[0, 0, 0, 0, 0, 1, 1, 0, 1, 0]
[0 0 0 0 0 1 1 0 1 0]
Multi-Label-Fashion-MNIST-master/274.png
[0, 0, 0, 1, 1, 0, 1, 1, 0, 0]
[0 0 0 1 1 0 1 1 0 0]
Multi-Label-Fashion-MNIST-master/275.png
[0, 0, 0, 0, 1, 0, 1, 0, 1, 0]
[0 0 0 0 1 0 1 0 1 0]
Multi-L

[1, 0, 1, 1, 0, 0, 0, 0, 1, 0]
[1 0 1 1 0 0 0 0 1 0]
Multi-Label-Fashion-MNIST-master/415.png
[0, 1, 0, 0, 0, 1, 0, 0, 0, 1]
[0 1 0 0 0 1 0 0 0 1]
Multi-Label-Fashion-MNIST-master/416.png
[0, 1, 0, 0, 1, 0, 0, 1, 0, 0]
[0 1 0 0 1 0 0 1 0 0]
Multi-Label-Fashion-MNIST-master/417.png
[0, 1, 0, 1, 0, 0, 0, 0, 1, 0]
[0 1 0 1 0 0 0 0 1 0]
Multi-Label-Fashion-MNIST-master/418.png
[0, 1, 0, 0, 0, 1, 0, 1, 0, 0]
[0 1 0 0 0 1 0 1 0 0]
Multi-Label-Fashion-MNIST-master/419.png
[0, 1, 1, 1, 0, 0, 0, 0, 0, 0]
[0 1 1 1 0 0 0 0 0 0]
Multi-Label-Fashion-MNIST-master/420.png
[1, 0, 0, 0, 0, 1, 0, 0, 1, 0]
[1 0 0 0 0 1 0 0 1 0]
Multi-Label-Fashion-MNIST-master/421.png
[1, 0, 0, 0, 0, 1, 1, 1, 0, 0]
[1 0 0 0 0 1 1 1 0 0]
Multi-Label-Fashion-MNIST-master/422.png
[0, 0, 0, 1, 0, 0, 0, 0, 1, 1]
[0 0 0 1 0 0 0 0 1 1]
Multi-Label-Fashion-MNIST-master/423.png
[0, 0, 1, 0, 1, 0, 0, 0, 0, 1]
[0 0 1 0 1 0 0 0 0 1]
Multi-Label-Fashion-MNIST-master/424.png
[0, 1, 0, 0, 0, 0, 1, 0, 1, 1]
[0 1 0 0 0 0 1 0 1 1]
Multi-L

[0, 1, 1, 0, 0, 0, 1, 0, 0, 0]
[0 1 1 0 0 0 1 0 0 0]
Multi-Label-Fashion-MNIST-master/567.png
[0, 0, 0, 1, 0, 0, 0, 1, 0, 1]
[0 0 0 1 0 0 0 1 0 1]
Multi-Label-Fashion-MNIST-master/568.png
[0, 1, 0, 0, 1, 0, 1, 0, 0, 0]
[0 1 0 0 1 0 1 0 0 0]
Multi-Label-Fashion-MNIST-master/569.png
[0, 1, 0, 0, 0, 1, 0, 1, 0, 0]
[0 1 0 0 0 1 0 1 0 0]
Multi-Label-Fashion-MNIST-master/570.png
[1, 1, 0, 0, 0, 0, 1, 1, 0, 0]
[1 1 0 0 0 0 1 1 0 0]
Multi-Label-Fashion-MNIST-master/571.png
[0, 0, 1, 0, 1, 1, 0, 0, 0, 1]
[0 0 1 0 1 1 0 0 0 1]
Multi-Label-Fashion-MNIST-master/572.png
[1, 0, 0, 0, 1, 0, 1, 1, 0, 0]
[1 0 0 0 1 0 1 1 0 0]
Multi-Label-Fashion-MNIST-master/573.png
[0, 1, 0, 0, 0, 0, 0, 0, 1, 1]
[0 1 0 0 0 0 0 0 1 1]
Multi-Label-Fashion-MNIST-master/574.png
[0, 1, 0, 1, 0, 0, 0, 0, 1, 0]
[0 1 0 1 0 0 0 0 1 0]
Multi-Label-Fashion-MNIST-master/575.png
[1, 0, 1, 0, 0, 0, 0, 0, 1, 1]
[1 0 1 0 0 0 0 0 1 1]
Multi-Label-Fashion-MNIST-master/576.png
[1, 0, 1, 0, 1, 1, 0, 0, 0, 0]
[1 0 1 0 1 1 0 0 0 0]
Multi-L

[1, 0, 0, 0, 1, 0, 0, 0, 1, 0]
[1 0 0 0 1 0 0 0 1 0]
Multi-Label-Fashion-MNIST-master/729.png
[0, 0, 0, 0, 1, 1, 1, 0, 0, 1]
[0 0 0 0 1 1 1 0 0 1]
Multi-Label-Fashion-MNIST-master/730.png
[0, 1, 0, 1, 0, 0, 0, 0, 1, 0]
[0 1 0 1 0 0 0 0 1 0]
Multi-Label-Fashion-MNIST-master/731.png
[0, 0, 0, 0, 0, 0, 0, 0, 1, 1]
[0 0 0 0 0 0 0 0 1 1]
Multi-Label-Fashion-MNIST-master/732.png
[0, 0, 1, 1, 0, 0, 0, 1, 0, 0]
[0 0 1 1 0 0 0 1 0 0]
Multi-Label-Fashion-MNIST-master/733.png
[1, 0, 0, 0, 0, 0, 1, 0, 1, 0]
[1 0 0 0 0 0 1 0 1 0]
Multi-Label-Fashion-MNIST-master/734.png
[0, 1, 0, 0, 1, 0, 0, 1, 1, 0]
[0 1 0 0 1 0 0 1 1 0]
Multi-Label-Fashion-MNIST-master/735.png
[1, 0, 0, 0, 1, 0, 1, 0, 0, 1]
[1 0 0 0 1 0 1 0 0 1]
Multi-Label-Fashion-MNIST-master/736.png
[0, 1, 0, 1, 0, 1, 0, 1, 0, 0]
[0 1 0 1 0 1 0 1 0 0]
Multi-Label-Fashion-MNIST-master/737.png
[1, 0, 1, 0, 1, 0, 0, 1, 0, 0]
[1 0 1 0 1 0 0 1 0 0]
Multi-Label-Fashion-MNIST-master/738.png
[1, 0, 0, 0, 1, 1, 0, 1, 0, 0]
[1 0 0 0 1 1 0 1 0 0]
Multi-L

[1, 1, 0, 0, 1, 0, 0, 0, 0, 0]
[1 1 0 0 1 0 0 0 0 0]
Multi-Label-Fashion-MNIST-master/857.png
[1, 0, 1, 0, 1, 0, 0, 0, 0, 0]
[1 0 1 0 1 0 0 0 0 0]
Multi-Label-Fashion-MNIST-master/858.png
[0, 1, 1, 0, 1, 1, 0, 0, 0, 0]
[0 1 1 0 1 1 0 0 0 0]
Multi-Label-Fashion-MNIST-master/859.png
[0, 1, 1, 0, 0, 1, 0, 1, 0, 0]
[0 1 1 0 0 1 0 1 0 0]
Multi-Label-Fashion-MNIST-master/860.png
[1, 0, 1, 1, 0, 0, 0, 1, 0, 0]
[1 0 1 1 0 0 0 1 0 0]
Multi-Label-Fashion-MNIST-master/861.png
[1, 1, 0, 0, 1, 0, 0, 0, 1, 0]
[1 1 0 0 1 0 0 0 1 0]
Multi-Label-Fashion-MNIST-master/862.png
[1, 0, 0, 0, 0, 0, 0, 0, 0, 1]
[1 0 0 0 0 0 0 0 0 1]
Multi-Label-Fashion-MNIST-master/863.png
[1, 0, 0, 0, 0, 0, 0, 1, 1, 0]
[1 0 0 0 0 0 0 1 1 0]
Multi-Label-Fashion-MNIST-master/864.png
[1, 0, 1, 1, 0, 0, 0, 0, 0, 0]
[1 0 1 1 0 0 0 0 0 0]
Multi-Label-Fashion-MNIST-master/865.png
[1, 1, 0, 0, 0, 0, 0, 1, 0, 0]
[1 1 0 0 0 0 0 1 0 0]
Multi-Label-Fashion-MNIST-master/866.png
[1, 0, 0, 0, 0, 0, 1, 0, 1, 0]
[1 0 0 0 0 0 1 0 1 0]
Multi-L

[0, 0, 0, 0, 1, 1, 1, 0, 0, 0]
[0 0 0 0 1 1 1 0 0 0]
Multi-Label-Fashion-MNIST-master/993.png
[1, 0, 0, 1, 0, 0, 0, 0, 0, 1]
[1 0 0 1 0 0 0 0 0 1]
Multi-Label-Fashion-MNIST-master/994.png
[1, 0, 0, 0, 0, 0, 0, 1, 1, 0]
[1 0 0 0 0 0 0 1 1 0]
Multi-Label-Fashion-MNIST-master/995.png
[0, 1, 0, 0, 0, 1, 1, 0, 0, 1]
[0 1 0 0 0 1 1 0 0 1]
Multi-Label-Fashion-MNIST-master/996.png
[0, 1, 0, 0, 1, 0, 0, 1, 1, 0]
[0 1 0 0 1 0 0 1 1 0]
Multi-Label-Fashion-MNIST-master/997.png
[0, 0, 0, 0, 0, 0, 1, 1, 1, 0]
[0 0 0 0 0 0 1 1 1 0]
Multi-Label-Fashion-MNIST-master/998.png
[1, 0, 0, 0, 1, 0, 0, 1, 0, 1]
[1 0 0 0 1 0 0 1 0 1]
Multi-Label-Fashion-MNIST-master/999.png
[1, 0, 0, 1, 0, 1, 0, 1, 0, 0]
[1 0 0 1 0 1 0 1 0 0]
Multi-Label-Fashion-MNIST-master/1000.png
[0, 0, 1, 0, 0, 0, 1, 1, 1, 0]
[0 0 1 0 0 0 1 1 1 0]
Multi-Label-Fashion-MNIST-master/1001.png
[0, 1, 0, 0, 0, 1, 0, 0, 1, 1]
[0 1 0 0 0 1 0 0 1 1]
Multi-Label-Fashion-MNIST-master/1002.png
[0, 1, 0, 0, 1, 1, 1, 0, 0, 0]
[0 1 0 0 1 1 1 0 0 0]
Mult

[0, 1, 1, 0, 0, 0, 0, 0, 1, 0]
[0 1 1 0 0 0 0 0 1 0]
Multi-Label-Fashion-MNIST-master/1141.png
[1, 1, 0, 0, 0, 1, 1, 0, 0, 0]
[1 1 0 0 0 1 1 0 0 0]
Multi-Label-Fashion-MNIST-master/1142.png
[1, 0, 1, 1, 0, 0, 0, 0, 0, 0]
[1 0 1 1 0 0 0 0 0 0]
Multi-Label-Fashion-MNIST-master/1143.png
[1, 0, 0, 0, 0, 1, 0, 0, 1, 0]
[1 0 0 0 0 1 0 0 1 0]
Multi-Label-Fashion-MNIST-master/1144.png
[0, 1, 0, 0, 0, 1, 0, 1, 1, 0]
[0 1 0 0 0 1 0 1 1 0]
Multi-Label-Fashion-MNIST-master/1145.png
[0, 0, 1, 0, 0, 0, 1, 1, 1, 0]
[0 0 1 0 0 0 1 1 1 0]
Multi-Label-Fashion-MNIST-master/1146.png
[0, 1, 0, 0, 0, 1, 0, 0, 0, 0]
[0 1 0 0 0 1 0 0 0 0]
Multi-Label-Fashion-MNIST-master/1147.png
[0, 1, 0, 1, 0, 0, 0, 1, 0, 1]
[0 1 0 1 0 0 0 1 0 1]
Multi-Label-Fashion-MNIST-master/1148.png
[0, 1, 1, 0, 1, 0, 1, 0, 0, 0]
[0 1 1 0 1 0 1 0 0 0]
Multi-Label-Fashion-MNIST-master/1149.png
[1, 0, 0, 0, 1, 1, 0, 1, 0, 0]
[1 0 0 0 1 1 0 1 0 0]
Multi-Label-Fashion-MNIST-master/1150.png
[1, 0, 1, 0, 0, 0, 0, 1, 0, 1]
[1 0 1 0 0 0 0 1 0 

[0, 1, 0, 0, 1, 1, 0, 0, 0, 1]
[0 1 0 0 1 1 0 0 0 1]
Multi-Label-Fashion-MNIST-master/1294.png
[0, 0, 0, 0, 0, 0, 1, 0, 0, 1]
[0 0 0 0 0 0 1 0 0 1]
Multi-Label-Fashion-MNIST-master/1295.png
[0, 1, 1, 0, 1, 0, 0, 0, 0, 0]
[0 1 1 0 1 0 0 0 0 0]
Multi-Label-Fashion-MNIST-master/1296.png
[0, 0, 0, 0, 1, 1, 1, 0, 0, 0]
[0 0 0 0 1 1 1 0 0 0]
Multi-Label-Fashion-MNIST-master/1297.png
[0, 1, 0, 0, 1, 0, 0, 0, 1, 0]
[0 1 0 0 1 0 0 0 1 0]
Multi-Label-Fashion-MNIST-master/1298.png
[0, 0, 1, 1, 0, 0, 1, 0, 0, 1]
[0 0 1 1 0 0 1 0 0 1]
Multi-Label-Fashion-MNIST-master/1299.png
[0, 0, 0, 1, 1, 1, 0, 0, 0, 0]
[0 0 0 1 1 1 0 0 0 0]
Multi-Label-Fashion-MNIST-master/1300.png
[0, 1, 1, 0, 0, 1, 0, 0, 0, 1]
[0 1 1 0 0 1 0 0 0 1]
Multi-Label-Fashion-MNIST-master/1301.png
[0, 0, 0, 1, 0, 1, 1, 1, 0, 0]
[0 0 0 1 0 1 1 1 0 0]
Multi-Label-Fashion-MNIST-master/1302.png
[1, 1, 0, 0, 0, 1, 0, 0, 1, 0]
[1 1 0 0 0 1 0 0 1 0]
Multi-Label-Fashion-MNIST-master/1303.png
[0, 0, 0, 0, 0, 1, 0, 1, 1, 1]
[0 0 0 0 0 1 0 1 1 

[0, 0, 0, 0, 1, 0, 0, 1, 0, 0]
[0 0 0 0 1 0 0 1 0 0]
Multi-Label-Fashion-MNIST-master/1462.png
[1, 1, 0, 0, 0, 0, 0, 1, 0, 1]
[1 1 0 0 0 0 0 1 0 1]
Multi-Label-Fashion-MNIST-master/1463.png
[1, 0, 0, 0, 1, 0, 1, 0, 1, 0]
[1 0 0 0 1 0 1 0 1 0]
Multi-Label-Fashion-MNIST-master/1464.png
[1, 1, 0, 0, 0, 1, 0, 0, 0, 1]
[1 1 0 0 0 1 0 0 0 1]
Multi-Label-Fashion-MNIST-master/1465.png
[1, 0, 0, 0, 1, 1, 0, 0, 1, 0]
[1 0 0 0 1 1 0 0 1 0]
Multi-Label-Fashion-MNIST-master/1466.png
[1, 0, 0, 0, 0, 0, 0, 1, 1, 0]
[1 0 0 0 0 0 0 1 1 0]
Multi-Label-Fashion-MNIST-master/1467.png
[0, 1, 0, 0, 0, 0, 1, 1, 0, 1]
[0 1 0 0 0 0 1 1 0 1]
Multi-Label-Fashion-MNIST-master/1468.png
[0, 0, 1, 1, 0, 0, 0, 1, 0, 1]
[0 0 1 1 0 0 0 1 0 1]
Multi-Label-Fashion-MNIST-master/1469.png
[0, 0, 0, 0, 1, 0, 1, 0, 0, 1]
[0 0 0 0 1 0 1 0 0 1]
Multi-Label-Fashion-MNIST-master/1470.png
[0, 1, 0, 0, 0, 1, 0, 1, 1, 0]
[0 1 0 0 0 1 0 1 1 0]
Multi-Label-Fashion-MNIST-master/1471.png
[0, 0, 0, 1, 1, 1, 0, 0, 0, 0]
[0 0 0 1 1 1 0 0 0 

[1, 0, 0, 0, 0, 0, 1, 1, 0, 1]
[1 0 0 0 0 0 1 1 0 1]
Multi-Label-Fashion-MNIST-master/1599.png
[0, 0, 0, 1, 0, 0, 0, 1, 1, 0]
[0 0 0 1 0 0 0 1 1 0]
Multi-Label-Fashion-MNIST-master/1600.png
[1, 0, 0, 0, 0, 1, 1, 0, 0, 0]
[1 0 0 0 0 1 1 0 0 0]
Multi-Label-Fashion-MNIST-master/1601.png
[0, 0, 1, 1, 0, 0, 0, 0, 1, 0]
[0 0 1 1 0 0 0 0 1 0]
Multi-Label-Fashion-MNIST-master/1602.png
[1, 1, 0, 0, 1, 0, 1, 0, 0, 0]
[1 1 0 0 1 0 1 0 0 0]
Multi-Label-Fashion-MNIST-master/1603.png
[1, 1, 0, 0, 1, 0, 0, 0, 0, 0]
[1 1 0 0 1 0 0 0 0 0]
Multi-Label-Fashion-MNIST-master/1604.png
[0, 0, 0, 1, 1, 1, 1, 0, 0, 0]
[0 0 0 1 1 1 1 0 0 0]
Multi-Label-Fashion-MNIST-master/1605.png
[1, 0, 0, 0, 1, 0, 1, 0, 0, 0]
[1 0 0 0 1 0 1 0 0 0]
Multi-Label-Fashion-MNIST-master/1606.png
[0, 0, 0, 0, 1, 1, 0, 0, 0, 0]
[0 0 0 0 1 1 0 0 0 0]
Multi-Label-Fashion-MNIST-master/1607.png
[0, 0, 1, 0, 0, 0, 1, 0, 1, 0]
[0 0 1 0 0 0 1 0 1 0]
Multi-Label-Fashion-MNIST-master/1608.png
[0, 0, 0, 0, 0, 1, 1, 1, 1, 0]
[0 0 0 0 0 1 1 1 1 

[0, 1, 0, 1, 0, 0, 0, 0, 1, 0]
[0 1 0 1 0 0 0 0 1 0]
Multi-Label-Fashion-MNIST-master/1748.png
[0, 0, 0, 1, 1, 0, 0, 1, 0, 0]
[0 0 0 1 1 0 0 1 0 0]
Multi-Label-Fashion-MNIST-master/1749.png
[1, 0, 0, 0, 0, 1, 0, 1, 0, 1]
[1 0 0 0 0 1 0 1 0 1]
Multi-Label-Fashion-MNIST-master/1750.png
[1, 1, 0, 1, 0, 0, 0, 0, 0, 0]
[1 1 0 1 0 0 0 0 0 0]
Multi-Label-Fashion-MNIST-master/1751.png
[1, 0, 0, 0, 1, 0, 0, 1, 0, 1]
[1 0 0 0 1 0 0 1 0 1]
Multi-Label-Fashion-MNIST-master/1752.png
[1, 0, 0, 0, 0, 1, 0, 0, 0, 0]
[1 0 0 0 0 1 0 0 0 0]
Multi-Label-Fashion-MNIST-master/1753.png
[0, 1, 0, 0, 0, 0, 1, 0, 1, 0]
[0 1 0 0 0 0 1 0 1 0]
Multi-Label-Fashion-MNIST-master/1754.png
[0, 0, 1, 1, 0, 0, 0, 1, 0, 0]
[0 0 1 1 0 0 0 1 0 0]
Multi-Label-Fashion-MNIST-master/1755.png
[0, 0, 1, 0, 1, 0, 1, 0, 1, 0]
[0 0 1 0 1 0 1 0 1 0]
Multi-Label-Fashion-MNIST-master/1756.png
[1, 0, 0, 0, 0, 0, 1, 1, 1, 0]
[1 0 0 0 0 0 1 1 1 0]
Multi-Label-Fashion-MNIST-master/1757.png
[0, 0, 0, 0, 1, 1, 0, 1, 0, 0]
[0 0 0 0 1 1 0 1 0 

[0, 0, 0, 0, 0, 0, 0, 1, 1, 1]
[0 0 0 0 0 0 0 1 1 1]
Multi-Label-Fashion-MNIST-master/1878.png
[1, 1, 0, 1, 1, 0, 0, 0, 0, 0]
[1 1 0 1 1 0 0 0 0 0]
Multi-Label-Fashion-MNIST-master/1879.png
[1, 0, 0, 0, 0, 1, 0, 0, 1, 0]
[1 0 0 0 0 1 0 0 1 0]
Multi-Label-Fashion-MNIST-master/1880.png
[1, 0, 0, 0, 1, 0, 0, 0, 0, 1]
[1 0 0 0 1 0 0 0 0 1]
Multi-Label-Fashion-MNIST-master/1881.png
[0, 0, 0, 0, 1, 0, 0, 1, 0, 1]
[0 0 0 0 1 0 0 1 0 1]
Multi-Label-Fashion-MNIST-master/1882.png
[1, 0, 0, 0, 0, 1, 0, 0, 0, 1]
[1 0 0 0 0 1 0 0 0 1]
Multi-Label-Fashion-MNIST-master/1883.png
[0, 0, 0, 1, 0, 0, 0, 1, 1, 1]
[0 0 0 1 0 0 0 1 1 1]
Multi-Label-Fashion-MNIST-master/1884.png
[0, 1, 0, 1, 1, 0, 0, 1, 0, 0]
[0 1 0 1 1 0 0 1 0 0]
Multi-Label-Fashion-MNIST-master/1885.png
[0, 0, 1, 1, 0, 0, 1, 0, 0, 1]
[0 0 1 1 0 0 1 0 0 1]
Multi-Label-Fashion-MNIST-master/1886.png
[1, 1, 0, 0, 0, 0, 0, 1, 0, 0]
[1 1 0 0 0 0 0 1 0 0]
Multi-Label-Fashion-MNIST-master/1887.png
[1, 0, 0, 1, 1, 0, 0, 0, 0, 0]
[1 0 0 1 1 0 0 0 0 

[0, 0, 0, 1, 1, 0, 0, 1, 0, 0]
[0 0 0 1 1 0 0 1 0 0]
Multi-Label-Fashion-MNIST-master/2012.png
[0, 0, 1, 1, 0, 0, 0, 1, 0, 1]
[0 0 1 1 0 0 0 1 0 1]
Multi-Label-Fashion-MNIST-master/2013.png
[1, 0, 0, 0, 0, 1, 1, 0, 0, 0]
[1 0 0 0 0 1 1 0 0 0]
Multi-Label-Fashion-MNIST-master/2014.png
[0, 0, 0, 0, 1, 1, 0, 1, 1, 0]
[0 0 0 0 1 1 0 1 1 0]
Multi-Label-Fashion-MNIST-master/2015.png
[0, 0, 0, 1, 1, 0, 0, 0, 1, 0]
[0 0 0 1 1 0 0 0 1 0]
Multi-Label-Fashion-MNIST-master/2016.png
[0, 0, 1, 0, 1, 0, 0, 0, 0, 0]
[0 0 1 0 1 0 0 0 0 0]
Multi-Label-Fashion-MNIST-master/2017.png
[0, 1, 1, 0, 1, 0, 0, 0, 0, 0]
[0 1 1 0 1 0 0 0 0 0]
Multi-Label-Fashion-MNIST-master/2018.png
[0, 1, 0, 0, 1, 0, 0, 1, 0, 0]
[0 1 0 0 1 0 0 1 0 0]
Multi-Label-Fashion-MNIST-master/2019.png
[0, 0, 0, 1, 0, 1, 0, 0, 1, 0]
[0 0 0 1 0 1 0 0 1 0]
Multi-Label-Fashion-MNIST-master/2020.png
[0, 0, 0, 1, 0, 1, 0, 0, 1, 0]
[0 0 0 1 0 1 0 0 1 0]
Multi-Label-Fashion-MNIST-master/2021.png
[1, 0, 0, 0, 1, 0, 1, 1, 0, 0]
[1 0 0 0 1 0 1 1 0 

[1, 1, 0, 0, 0, 1, 0, 1, 0, 0]
[1 1 0 0 0 1 0 1 0 0]
Multi-Label-Fashion-MNIST-master/2156.png
[1, 0, 1, 0, 0, 1, 0, 0, 0, 0]
[1 0 1 0 0 1 0 0 0 0]
Multi-Label-Fashion-MNIST-master/2157.png
[1, 1, 0, 0, 0, 0, 1, 0, 0, 0]
[1 1 0 0 0 0 1 0 0 0]
Multi-Label-Fashion-MNIST-master/2158.png
[1, 0, 1, 1, 0, 0, 1, 0, 0, 0]
[1 0 1 1 0 0 1 0 0 0]
Multi-Label-Fashion-MNIST-master/2159.png
[0, 1, 0, 0, 1, 1, 0, 1, 0, 0]
[0 1 0 0 1 1 0 1 0 0]
Multi-Label-Fashion-MNIST-master/2160.png
[0, 1, 0, 1, 0, 0, 1, 1, 0, 0]
[0 1 0 1 0 0 1 1 0 0]
Multi-Label-Fashion-MNIST-master/2161.png
[0, 0, 0, 0, 1, 1, 1, 0, 0, 1]
[0 0 0 0 1 1 1 0 0 1]
Multi-Label-Fashion-MNIST-master/2162.png
[1, 0, 1, 0, 1, 0, 0, 0, 0, 0]
[1 0 1 0 1 0 0 0 0 0]
Multi-Label-Fashion-MNIST-master/2163.png
[1, 0, 1, 1, 0, 0, 0, 0, 0, 1]
[1 0 1 1 0 0 0 0 0 1]
Multi-Label-Fashion-MNIST-master/2164.png
[0, 0, 0, 1, 1, 1, 0, 0, 1, 0]
[0 0 0 1 1 1 0 0 1 0]
Multi-Label-Fashion-MNIST-master/2165.png
[1, 0, 0, 0, 0, 0, 1, 0, 1, 1]
[1 0 0 0 0 0 1 0 1 

[1, 0, 0, 0, 0, 1, 0, 0, 1, 0]
[1 0 0 0 0 1 0 0 1 0]
Multi-Label-Fashion-MNIST-master/2272.png
[0, 0, 0, 1, 1, 0, 0, 0, 0, 1]
[0 0 0 1 1 0 0 0 0 1]
Multi-Label-Fashion-MNIST-master/2273.png
[0, 0, 0, 1, 1, 0, 0, 1, 0, 0]
[0 0 0 1 1 0 0 1 0 0]
Multi-Label-Fashion-MNIST-master/2274.png
[0, 0, 1, 1, 0, 0, 0, 0, 1, 0]
[0 0 1 1 0 0 0 0 1 0]
Multi-Label-Fashion-MNIST-master/2275.png
[1, 0, 0, 1, 0, 0, 1, 0, 0, 0]
[1 0 0 1 0 0 1 0 0 0]
Multi-Label-Fashion-MNIST-master/2276.png
[1, 0, 0, 1, 1, 0, 0, 0, 1, 0]
[1 0 0 1 1 0 0 0 1 0]
Multi-Label-Fashion-MNIST-master/2277.png
[0, 0, 1, 0, 0, 0, 1, 1, 0, 1]
[0 0 1 0 0 0 1 1 0 1]
Multi-Label-Fashion-MNIST-master/2278.png
[0, 0, 0, 1, 0, 1, 1, 0, 0, 0]
[0 0 0 1 0 1 1 0 0 0]
Multi-Label-Fashion-MNIST-master/2279.png
[0, 0, 1, 0, 0, 0, 0, 1, 0, 1]
[0 0 1 0 0 0 0 1 0 1]
Multi-Label-Fashion-MNIST-master/2280.png
[0, 1, 1, 1, 0, 0, 0, 0, 0, 0]
[0 1 1 1 0 0 0 0 0 0]
Multi-Label-Fashion-MNIST-master/2281.png
[1, 0, 1, 0, 0, 0, 0, 1, 1, 0]
[1 0 1 0 0 0 0 1 1 

[0, 1, 0, 1, 1, 0, 0, 1, 0, 0]
[0 1 0 1 1 0 0 1 0 0]
Multi-Label-Fashion-MNIST-master/2402.png
[0, 1, 0, 0, 0, 0, 1, 0, 0, 1]
[0 1 0 0 0 0 1 0 0 1]
Multi-Label-Fashion-MNIST-master/2403.png
[0, 1, 0, 0, 0, 0, 1, 0, 0, 1]
[0 1 0 0 0 0 1 0 0 1]
Multi-Label-Fashion-MNIST-master/2404.png
[1, 0, 0, 0, 1, 0, 0, 0, 1, 0]
[1 0 0 0 1 0 0 0 1 0]
Multi-Label-Fashion-MNIST-master/2405.png
[1, 1, 0, 0, 0, 0, 1, 0, 0, 1]
[1 1 0 0 0 0 1 0 0 1]
Multi-Label-Fashion-MNIST-master/2406.png
[1, 0, 0, 0, 1, 0, 0, 1, 0, 1]
[1 0 0 0 1 0 0 1 0 1]
Multi-Label-Fashion-MNIST-master/2407.png
[1, 0, 0, 0, 0, 0, 1, 1, 0, 1]
[1 0 0 0 0 0 1 1 0 1]
Multi-Label-Fashion-MNIST-master/2408.png
[0, 0, 0, 0, 1, 0, 1, 1, 0, 1]
[0 0 0 0 1 0 1 1 0 1]
Multi-Label-Fashion-MNIST-master/2409.png
[0, 0, 0, 1, 0, 0, 0, 1, 0, 1]
[0 0 0 1 0 0 0 1 0 1]
Multi-Label-Fashion-MNIST-master/2410.png
[0, 1, 0, 0, 0, 0, 0, 1, 0, 1]
[0 1 0 0 0 0 0 1 0 1]
Multi-Label-Fashion-MNIST-master/2411.png
[0, 1, 0, 0, 1, 0, 0, 1, 1, 0]
[0 1 0 0 1 0 0 1 1 

[0, 0, 0, 1, 0, 0, 0, 1, 0, 0]
[0 0 0 1 0 0 0 1 0 0]
Multi-Label-Fashion-MNIST-master/2549.png
[1, 0, 0, 1, 0, 0, 1, 0, 0, 0]
[1 0 0 1 0 0 1 0 0 0]
Multi-Label-Fashion-MNIST-master/2550.png
[1, 0, 0, 0, 0, 0, 1, 0, 1, 0]
[1 0 0 0 0 0 1 0 1 0]
Multi-Label-Fashion-MNIST-master/2551.png
[1, 0, 0, 1, 0, 0, 0, 1, 0, 0]
[1 0 0 1 0 0 0 1 0 0]
Multi-Label-Fashion-MNIST-master/2552.png
[0, 0, 0, 0, 0, 0, 1, 0, 1, 1]
[0 0 0 0 0 0 1 0 1 1]
Multi-Label-Fashion-MNIST-master/2553.png
[1, 0, 1, 0, 0, 1, 0, 1, 0, 0]
[1 0 1 0 0 1 0 1 0 0]
Multi-Label-Fashion-MNIST-master/2554.png
[1, 0, 0, 0, 1, 0, 0, 0, 1, 1]
[1 0 0 0 1 0 0 0 1 1]
Multi-Label-Fashion-MNIST-master/2555.png
[1, 0, 1, 1, 0, 1, 0, 0, 0, 0]
[1 0 1 1 0 1 0 0 0 0]
Multi-Label-Fashion-MNIST-master/2556.png
[0, 0, 0, 0, 1, 1, 0, 0, 1, 1]
[0 0 0 0 1 1 0 0 1 1]
Multi-Label-Fashion-MNIST-master/2557.png
[0, 0, 0, 0, 0, 0, 1, 1, 0, 1]
[0 0 0 0 0 0 1 1 0 1]
Multi-Label-Fashion-MNIST-master/2558.png
[0, 1, 0, 1, 0, 0, 0, 1, 0, 0]
[0 1 0 1 0 0 0 1 0 

[1, 1, 0, 0, 0, 0, 0, 1, 1, 0]
[1 1 0 0 0 0 0 1 1 0]
Multi-Label-Fashion-MNIST-master/2716.png
[1, 1, 0, 0, 0, 0, 0, 0, 0, 0]
[1 1 0 0 0 0 0 0 0 0]
Multi-Label-Fashion-MNIST-master/2717.png
[1, 1, 0, 0, 0, 0, 0, 1, 0, 0]
[1 1 0 0 0 0 0 1 0 0]
Multi-Label-Fashion-MNIST-master/2718.png
[0, 0, 0, 1, 0, 1, 0, 0, 0, 1]
[0 0 0 1 0 1 0 0 0 1]
Multi-Label-Fashion-MNIST-master/2719.png
[0, 0, 1, 0, 0, 1, 0, 0, 0, 1]
[0 0 1 0 0 1 0 0 0 1]
Multi-Label-Fashion-MNIST-master/2720.png
[0, 0, 1, 0, 0, 0, 0, 1, 1, 0]
[0 0 1 0 0 0 0 1 1 0]
Multi-Label-Fashion-MNIST-master/2721.png
[0, 0, 0, 0, 1, 0, 1, 0, 1, 1]
[0 0 0 0 1 0 1 0 1 1]
Multi-Label-Fashion-MNIST-master/2722.png
[0, 1, 0, 0, 1, 0, 1, 1, 0, 0]
[0 1 0 0 1 0 1 1 0 0]
Multi-Label-Fashion-MNIST-master/2723.png
[0, 1, 0, 1, 0, 0, 0, 0, 1, 1]
[0 1 0 1 0 0 0 0 1 1]
Multi-Label-Fashion-MNIST-master/2724.png
[1, 0, 0, 0, 1, 1, 1, 0, 0, 0]
[1 0 0 0 1 1 1 0 0 0]
Multi-Label-Fashion-MNIST-master/2725.png
[0, 0, 1, 0, 0, 0, 1, 1, 1, 0]
[0 0 1 0 0 0 1 1 1 

[0, 0, 1, 1, 0, 0, 1, 0, 0, 0]
[0 0 1 1 0 0 1 0 0 0]
Multi-Label-Fashion-MNIST-master/2874.png
[0, 0, 0, 1, 1, 0, 0, 1, 0, 0]
[0 0 0 1 1 0 0 1 0 0]
Multi-Label-Fashion-MNIST-master/2875.png
[0, 0, 1, 0, 0, 0, 0, 1, 0, 1]
[0 0 1 0 0 0 0 1 0 1]
Multi-Label-Fashion-MNIST-master/2876.png
[0, 0, 1, 0, 0, 1, 1, 0, 0, 0]
[0 0 1 0 0 1 1 0 0 0]
Multi-Label-Fashion-MNIST-master/2877.png
[1, 0, 0, 0, 0, 1, 0, 1, 0, 1]
[1 0 0 0 0 1 0 1 0 1]
Multi-Label-Fashion-MNIST-master/2878.png
[0, 0, 1, 0, 0, 1, 1, 0, 1, 0]
[0 0 1 0 0 1 1 0 1 0]
Multi-Label-Fashion-MNIST-master/2879.png
[1, 0, 0, 1, 0, 0, 1, 0, 0, 0]
[1 0 0 1 0 0 1 0 0 0]
Multi-Label-Fashion-MNIST-master/2880.png
[0, 1, 0, 1, 1, 0, 0, 0, 1, 0]
[0 1 0 1 1 0 0 0 1 0]
Multi-Label-Fashion-MNIST-master/2881.png
[1, 0, 0, 0, 1, 0, 0, 0, 1, 0]
[1 0 0 0 1 0 0 0 1 0]
Multi-Label-Fashion-MNIST-master/2882.png
[0, 1, 1, 0, 1, 0, 0, 0, 1, 0]
[0 1 1 0 1 0 0 0 1 0]
Multi-Label-Fashion-MNIST-master/2883.png
[0, 1, 0, 1, 0, 1, 0, 1, 0, 0]
[0 1 0 1 0 1 0 1 0 

[1, 0, 0, 0, 0, 1, 0, 0, 1, 0]
[1 0 0 0 0 1 0 0 1 0]
Multi-Label-Fashion-MNIST-master/3027.png
[1, 0, 1, 1, 0, 1, 0, 0, 0, 0]
[1 0 1 1 0 1 0 0 0 0]
Multi-Label-Fashion-MNIST-master/3028.png
[1, 0, 1, 1, 0, 0, 0, 0, 0, 0]
[1 0 1 1 0 0 0 0 0 0]
Multi-Label-Fashion-MNIST-master/3029.png
[0, 0, 0, 1, 1, 0, 1, 0, 0, 0]
[0 0 0 1 1 0 1 0 0 0]
Multi-Label-Fashion-MNIST-master/3030.png
[0, 0, 1, 0, 0, 0, 0, 1, 1, 1]
[0 0 1 0 0 0 0 1 1 1]
Multi-Label-Fashion-MNIST-master/3031.png
[0, 0, 0, 0, 1, 1, 0, 1, 0, 1]
[0 0 0 0 1 1 0 1 0 1]
Multi-Label-Fashion-MNIST-master/3032.png
[0, 1, 0, 0, 1, 0, 0, 1, 0, 1]
[0 1 0 0 1 0 0 1 0 1]
Multi-Label-Fashion-MNIST-master/3033.png
[1, 1, 0, 0, 0, 0, 0, 0, 0, 0]
[1 1 0 0 0 0 0 0 0 0]
Multi-Label-Fashion-MNIST-master/3034.png
[0, 0, 0, 0, 0, 1, 0, 1, 1, 1]
[0 0 0 0 0 1 0 1 1 1]
Multi-Label-Fashion-MNIST-master/3035.png
[0, 0, 1, 1, 0, 0, 0, 1, 1, 0]
[0 0 1 1 0 0 0 1 1 0]
Multi-Label-Fashion-MNIST-master/3036.png
[0, 1, 0, 0, 0, 0, 1, 1, 0, 0]
[0 1 0 0 0 0 1 1 0 

[0, 0, 0, 0, 0, 0, 0, 0, 1, 1]
[0 0 0 0 0 0 0 0 1 1]
Multi-Label-Fashion-MNIST-master/3170.png
[1, 0, 1, 0, 0, 0, 0, 1, 1, 0]
[1 0 1 0 0 0 0 1 1 0]
Multi-Label-Fashion-MNIST-master/3171.png
[1, 0, 0, 0, 0, 0, 0, 1, 0, 1]
[1 0 0 0 0 0 0 1 0 1]
Multi-Label-Fashion-MNIST-master/3172.png
[1, 0, 0, 0, 1, 0, 0, 0, 1, 1]
[1 0 0 0 1 0 0 0 1 1]
Multi-Label-Fashion-MNIST-master/3173.png
[1, 0, 1, 1, 0, 0, 0, 0, 1, 0]
[1 0 1 1 0 0 0 0 1 0]
Multi-Label-Fashion-MNIST-master/3174.png
[0, 0, 1, 0, 0, 1, 0, 1, 0, 1]
[0 0 1 0 0 1 0 1 0 1]
Multi-Label-Fashion-MNIST-master/3175.png
[0, 0, 1, 0, 0, 1, 0, 0, 0, 1]
[0 0 1 0 0 1 0 0 0 1]
Multi-Label-Fashion-MNIST-master/3176.png
[0, 0, 0, 0, 1, 1, 0, 0, 1, 1]
[0 0 0 0 1 1 0 0 1 1]
Multi-Label-Fashion-MNIST-master/3177.png
[0, 1, 1, 0, 0, 0, 1, 0, 1, 0]
[0 1 1 0 0 0 1 0 1 0]
Multi-Label-Fashion-MNIST-master/3178.png
[0, 0, 0, 0, 1, 1, 0, 0, 0, 0]
[0 0 0 0 1 1 0 0 0 0]
Multi-Label-Fashion-MNIST-master/3179.png
[0, 0, 0, 1, 1, 0, 1, 1, 0, 0]
[0 0 0 1 1 0 1 1 0 

[1, 0, 0, 0, 0, 1, 0, 1, 1, 0]
[1 0 0 0 0 1 0 1 1 0]
Multi-Label-Fashion-MNIST-master/3323.png
[0, 1, 0, 1, 0, 1, 0, 0, 0, 1]
[0 1 0 1 0 1 0 0 0 1]
Multi-Label-Fashion-MNIST-master/3324.png
[1, 0, 1, 0, 1, 0, 0, 0, 0, 1]
[1 0 1 0 1 0 0 0 0 1]
Multi-Label-Fashion-MNIST-master/3325.png
[0, 0, 1, 1, 0, 0, 0, 1, 0, 0]
[0 0 1 1 0 0 0 1 0 0]
Multi-Label-Fashion-MNIST-master/3326.png
[1, 1, 0, 1, 0, 0, 0, 1, 0, 0]
[1 1 0 1 0 0 0 1 0 0]
Multi-Label-Fashion-MNIST-master/3327.png
[1, 0, 0, 0, 0, 0, 1, 0, 1, 0]
[1 0 0 0 0 0 1 0 1 0]
Multi-Label-Fashion-MNIST-master/3328.png
[0, 0, 1, 1, 0, 0, 1, 0, 0, 0]
[0 0 1 1 0 0 1 0 0 0]
Multi-Label-Fashion-MNIST-master/3329.png
[1, 0, 0, 1, 0, 0, 1, 0, 0, 1]
[1 0 0 1 0 0 1 0 0 1]
Multi-Label-Fashion-MNIST-master/3330.png
[0, 0, 0, 0, 1, 0, 0, 1, 1, 0]
[0 0 0 0 1 0 0 1 1 0]
Multi-Label-Fashion-MNIST-master/3331.png
[1, 1, 0, 0, 0, 0, 1, 0, 0, 1]
[1 1 0 0 0 0 1 0 0 1]
Multi-Label-Fashion-MNIST-master/3332.png
[0, 1, 0, 0, 1, 0, 0, 1, 1, 0]
[0 1 0 0 1 0 0 1 1 

[1, 0, 0, 0, 0, 0, 0, 0, 1, 1]
[1 0 0 0 0 0 0 0 1 1]
Multi-Label-Fashion-MNIST-master/3479.png
[0, 1, 0, 0, 1, 0, 0, 0, 1, 1]
[0 1 0 0 1 0 0 0 1 1]
Multi-Label-Fashion-MNIST-master/3480.png
[0, 1, 1, 0, 0, 0, 0, 1, 0, 1]
[0 1 1 0 0 0 0 1 0 1]
Multi-Label-Fashion-MNIST-master/3481.png
[0, 1, 0, 0, 1, 0, 1, 0, 0, 1]
[0 1 0 0 1 0 1 0 0 1]
Multi-Label-Fashion-MNIST-master/3482.png
[1, 0, 0, 0, 1, 0, 0, 0, 1, 0]
[1 0 0 0 1 0 0 0 1 0]
Multi-Label-Fashion-MNIST-master/3483.png
[1, 1, 0, 0, 1, 0, 0, 0, 1, 0]
[1 1 0 0 1 0 0 0 1 0]
Multi-Label-Fashion-MNIST-master/3484.png
[1, 0, 1, 1, 0, 0, 0, 0, 1, 0]
[1 0 1 1 0 0 0 0 1 0]
Multi-Label-Fashion-MNIST-master/3485.png
[0, 1, 0, 0, 0, 0, 1, 0, 1, 0]
[0 1 0 0 0 0 1 0 1 0]
Multi-Label-Fashion-MNIST-master/3486.png
[0, 0, 0, 0, 0, 0, 1, 1, 0, 1]
[0 0 0 0 0 0 1 1 0 1]
Multi-Label-Fashion-MNIST-master/3487.png
[0, 1, 0, 1, 0, 0, 0, 0, 0, 1]
[0 1 0 1 0 0 0 0 0 1]
Multi-Label-Fashion-MNIST-master/3488.png
[1, 1, 0, 0, 0, 1, 1, 0, 0, 0]
[1 1 0 0 0 1 1 0 0 

[0, 1, 1, 1, 0, 0, 0, 0, 0, 1]
[0 1 1 1 0 0 0 0 0 1]
Multi-Label-Fashion-MNIST-master/3633.png
[1, 1, 0, 0, 0, 0, 0, 0, 0, 1]
[1 1 0 0 0 0 0 0 0 1]
Multi-Label-Fashion-MNIST-master/3634.png
[1, 1, 0, 0, 0, 1, 0, 1, 0, 0]
[1 1 0 0 0 1 0 1 0 0]
Multi-Label-Fashion-MNIST-master/3635.png
[1, 0, 0, 0, 0, 0, 0, 1, 1, 1]
[1 0 0 0 0 0 0 1 1 1]
Multi-Label-Fashion-MNIST-master/3636.png
[1, 0, 0, 0, 1, 0, 0, 0, 1, 0]
[1 0 0 0 1 0 0 0 1 0]
Multi-Label-Fashion-MNIST-master/3637.png
[1, 0, 0, 0, 0, 0, 1, 0, 0, 1]
[1 0 0 0 0 0 1 0 0 1]
Multi-Label-Fashion-MNIST-master/3638.png
[1, 0, 0, 1, 0, 0, 1, 0, 1, 0]
[1 0 0 1 0 0 1 0 1 0]
Multi-Label-Fashion-MNIST-master/3639.png
[0, 1, 0, 0, 0, 0, 1, 1, 0, 0]
[0 1 0 0 0 0 1 1 0 0]
Multi-Label-Fashion-MNIST-master/3640.png
[0, 0, 1, 0, 0, 1, 1, 0, 0, 1]
[0 0 1 0 0 1 1 0 0 1]
Multi-Label-Fashion-MNIST-master/3641.png
[0, 0, 1, 0, 0, 0, 0, 1, 0, 1]
[0 0 1 0 0 0 0 1 0 1]
Multi-Label-Fashion-MNIST-master/3642.png
[0, 0, 0, 0, 1, 1, 0, 1, 0, 0]
[0 0 0 0 1 1 0 1 0 

[0, 0, 0, 0, 0, 1, 1, 0, 0, 1]
[0 0 0 0 0 1 1 0 0 1]
Multi-Label-Fashion-MNIST-master/3800.png
[1, 0, 0, 0, 0, 0, 1, 0, 1, 1]
[1 0 0 0 0 0 1 0 1 1]
Multi-Label-Fashion-MNIST-master/3801.png
[0, 1, 1, 0, 0, 1, 0, 0, 1, 0]
[0 1 1 0 0 1 0 0 1 0]
Multi-Label-Fashion-MNIST-master/3802.png
[0, 1, 0, 0, 1, 1, 0, 0, 1, 0]
[0 1 0 0 1 1 0 0 1 0]
Multi-Label-Fashion-MNIST-master/3803.png
[0, 0, 0, 1, 1, 0, 0, 1, 0, 0]
[0 0 0 1 1 0 0 1 0 0]
Multi-Label-Fashion-MNIST-master/3804.png
[0, 1, 0, 0, 0, 1, 1, 1, 0, 0]
[0 1 0 0 0 1 1 1 0 0]
Multi-Label-Fashion-MNIST-master/3805.png
[1, 1, 0, 1, 0, 0, 0, 0, 1, 0]
[1 1 0 1 0 0 0 0 1 0]
Multi-Label-Fashion-MNIST-master/3806.png
[0, 1, 0, 0, 0, 1, 0, 0, 1, 0]
[0 1 0 0 0 1 0 0 1 0]
Multi-Label-Fashion-MNIST-master/3807.png
[0, 0, 0, 0, 0, 0, 0, 1, 0, 1]
[0 0 0 0 0 0 0 1 0 1]
Multi-Label-Fashion-MNIST-master/3808.png
[1, 1, 0, 1, 0, 0, 0, 0, 0, 0]
[1 1 0 1 0 0 0 0 0 0]
Multi-Label-Fashion-MNIST-master/3809.png
[0, 0, 0, 1, 0, 0, 0, 0, 0, 1]
[0 0 0 1 0 0 0 0 0 

[0, 0, 0, 0, 0, 1, 0, 1, 0, 1]
[0 0 0 0 0 1 0 1 0 1]
Multi-Label-Fashion-MNIST-master/3940.png
[0, 1, 0, 0, 0, 1, 1, 0, 0, 1]
[0 1 0 0 0 1 1 0 0 1]
Multi-Label-Fashion-MNIST-master/3941.png
[0, 1, 0, 0, 0, 1, 1, 1, 0, 0]
[0 1 0 0 0 1 1 1 0 0]
Multi-Label-Fashion-MNIST-master/3942.png
[0, 0, 1, 1, 0, 0, 0, 1, 0, 0]
[0 0 1 1 0 0 0 1 0 0]
Multi-Label-Fashion-MNIST-master/3943.png
[0, 0, 0, 0, 1, 0, 1, 0, 0, 0]
[0 0 0 0 1 0 1 0 0 0]
Multi-Label-Fashion-MNIST-master/3944.png
[0, 0, 0, 1, 1, 0, 0, 1, 1, 0]
[0 0 0 1 1 0 0 1 1 0]
Multi-Label-Fashion-MNIST-master/3945.png
[0, 1, 0, 1, 1, 0, 0, 0, 1, 0]
[0 1 0 1 1 0 0 0 1 0]
Multi-Label-Fashion-MNIST-master/3946.png
[0, 1, 0, 1, 0, 0, 0, 1, 0, 1]
[0 1 0 1 0 0 0 1 0 1]
Multi-Label-Fashion-MNIST-master/3947.png
[1, 0, 0, 1, 0, 0, 0, 1, 0, 0]
[1 0 0 1 0 0 0 1 0 0]
Multi-Label-Fashion-MNIST-master/3948.png
[0, 0, 1, 1, 0, 0, 0, 0, 0, 1]
[0 0 1 1 0 0 0 0 0 1]
Multi-Label-Fashion-MNIST-master/3949.png
[0, 0, 1, 0, 0, 0, 1, 0, 1, 0]
[0 0 1 0 0 0 1 0 1 

[1, 0, 0, 1, 0, 0, 0, 0, 1, 1]
[1 0 0 1 0 0 0 0 1 1]
Multi-Label-Fashion-MNIST-master/4105.png
[0, 0, 1, 1, 0, 1, 1, 0, 0, 0]
[0 0 1 1 0 1 1 0 0 0]
Multi-Label-Fashion-MNIST-master/4106.png
[0, 0, 0, 0, 1, 1, 0, 1, 0, 1]
[0 0 0 0 1 1 0 1 0 1]
Multi-Label-Fashion-MNIST-master/4107.png
[0, 0, 1, 0, 0, 1, 0, 0, 1, 0]
[0 0 1 0 0 1 0 0 1 0]
Multi-Label-Fashion-MNIST-master/4108.png
[1, 1, 0, 0, 0, 0, 0, 0, 0, 1]
[1 1 0 0 0 0 0 0 0 1]
Multi-Label-Fashion-MNIST-master/4109.png
[0, 1, 0, 0, 0, 1, 1, 0, 1, 0]
[0 1 0 0 0 1 1 0 1 0]
Multi-Label-Fashion-MNIST-master/4110.png
[0, 0, 1, 0, 1, 0, 0, 0, 1, 1]
[0 0 1 0 1 0 0 0 1 1]
Multi-Label-Fashion-MNIST-master/4111.png
[1, 0, 0, 1, 1, 0, 0, 0, 0, 0]
[1 0 0 1 1 0 0 0 0 0]
Multi-Label-Fashion-MNIST-master/4112.png
[1, 0, 1, 1, 0, 1, 0, 0, 0, 0]
[1 0 1 1 0 1 0 0 0 0]
Multi-Label-Fashion-MNIST-master/4113.png
[0, 0, 0, 0, 0, 1, 1, 1, 0, 0]
[0 0 0 0 0 1 1 1 0 0]
Multi-Label-Fashion-MNIST-master/4114.png
[1, 0, 1, 0, 1, 0, 0, 0, 1, 0]
[1 0 1 0 1 0 0 0 1 

[1, 0, 0, 0, 1, 0, 1, 0, 1, 0]
[1 0 0 0 1 0 1 0 1 0]
Multi-Label-Fashion-MNIST-master/4260.png
[0, 1, 1, 0, 1, 0, 0, 0, 0, 0]
[0 1 1 0 1 0 0 0 0 0]
Multi-Label-Fashion-MNIST-master/4261.png
[0, 0, 1, 0, 0, 0, 1, 0, 0, 1]
[0 0 1 0 0 0 1 0 0 1]
Multi-Label-Fashion-MNIST-master/4262.png
[0, 0, 1, 0, 0, 0, 0, 1, 1, 0]
[0 0 1 0 0 0 0 1 1 0]
Multi-Label-Fashion-MNIST-master/4263.png
[0, 1, 0, 1, 1, 1, 0, 0, 0, 0]
[0 1 0 1 1 1 0 0 0 0]
Multi-Label-Fashion-MNIST-master/4264.png
[0, 0, 0, 0, 1, 0, 0, 1, 0, 0]
[0 0 0 0 1 0 0 1 0 0]
Multi-Label-Fashion-MNIST-master/4265.png
[0, 0, 0, 1, 0, 0, 0, 1, 0, 1]
[0 0 0 1 0 0 0 1 0 1]
Multi-Label-Fashion-MNIST-master/4266.png
[0, 1, 0, 1, 0, 0, 1, 0, 0, 1]
[0 1 0 1 0 0 1 0 0 1]
Multi-Label-Fashion-MNIST-master/4267.png
[0, 0, 0, 0, 1, 0, 0, 1, 1, 0]
[0 0 0 0 1 0 0 1 1 0]
Multi-Label-Fashion-MNIST-master/4268.png
[1, 1, 0, 0, 1, 0, 0, 0, 0, 0]
[1 1 0 0 1 0 0 0 0 0]
Multi-Label-Fashion-MNIST-master/4269.png
[0, 0, 0, 1, 0, 0, 0, 1, 1, 1]
[0 0 0 1 0 0 0 1 1 

[0, 0, 0, 0, 0, 0, 1, 1, 1, 0]
[0 0 0 0 0 0 1 1 1 0]
Multi-Label-Fashion-MNIST-master/4429.png
[0, 0, 0, 1, 1, 0, 1, 0, 1, 0]
[0 0 0 1 1 0 1 0 1 0]
Multi-Label-Fashion-MNIST-master/4430.png
[0, 0, 0, 1, 0, 0, 0, 0, 1, 0]
[0 0 0 1 0 0 0 0 1 0]
Multi-Label-Fashion-MNIST-master/4431.png
[0, 0, 0, 1, 0, 1, 0, 0, 0, 1]
[0 0 0 1 0 1 0 0 0 1]
Multi-Label-Fashion-MNIST-master/4432.png
[1, 0, 1, 0, 0, 0, 1, 0, 1, 0]
[1 0 1 0 0 0 1 0 1 0]
Multi-Label-Fashion-MNIST-master/4433.png
[0, 0, 1, 0, 0, 0, 1, 1, 0, 0]
[0 0 1 0 0 0 1 1 0 0]
Multi-Label-Fashion-MNIST-master/4434.png
[1, 0, 0, 0, 0, 1, 1, 0, 1, 0]
[1 0 0 0 0 1 1 0 1 0]
Multi-Label-Fashion-MNIST-master/4435.png
[0, 1, 0, 0, 0, 0, 1, 1, 0, 0]
[0 1 0 0 0 0 1 1 0 0]
Multi-Label-Fashion-MNIST-master/4436.png
[0, 0, 0, 0, 1, 1, 0, 0, 0, 1]
[0 0 0 0 1 1 0 0 0 1]
Multi-Label-Fashion-MNIST-master/4437.png
[0, 1, 1, 0, 1, 0, 0, 0, 0, 0]
[0 1 1 0 1 0 0 0 0 0]
Multi-Label-Fashion-MNIST-master/4438.png
[0, 0, 1, 0, 0, 0, 1, 0, 1, 1]
[0 0 1 0 0 0 1 0 1 

[0, 1, 0, 0, 0, 0, 1, 1, 1, 0]
[0 1 0 0 0 0 1 1 1 0]
Multi-Label-Fashion-MNIST-master/4589.png
[0, 1, 0, 0, 1, 1, 1, 0, 0, 0]
[0 1 0 0 1 1 1 0 0 0]
Multi-Label-Fashion-MNIST-master/4590.png
[1, 1, 0, 0, 0, 0, 0, 1, 0, 1]
[1 1 0 0 0 0 0 1 0 1]
Multi-Label-Fashion-MNIST-master/4591.png
[0, 0, 1, 0, 0, 0, 1, 0, 1, 1]
[0 0 1 0 0 0 1 0 1 1]
Multi-Label-Fashion-MNIST-master/4592.png
[0, 1, 0, 1, 1, 0, 0, 0, 0, 1]
[0 1 0 1 1 0 0 0 0 1]
Multi-Label-Fashion-MNIST-master/4593.png
[1, 0, 1, 0, 0, 1, 0, 1, 0, 0]
[1 0 1 0 0 1 0 1 0 0]
Multi-Label-Fashion-MNIST-master/4594.png
[0, 0, 1, 0, 0, 1, 0, 0, 0, 1]
[0 0 1 0 0 1 0 0 0 1]
Multi-Label-Fashion-MNIST-master/4595.png
[0, 0, 0, 0, 1, 0, 1, 1, 0, 1]
[0 0 0 0 1 0 1 1 0 1]
Multi-Label-Fashion-MNIST-master/4596.png
[0, 1, 1, 0, 0, 0, 1, 0, 0, 0]
[0 1 1 0 0 0 1 0 0 0]
Multi-Label-Fashion-MNIST-master/4597.png
[0, 0, 1, 1, 0, 1, 0, 0, 0, 0]
[0 0 1 1 0 1 0 0 0 0]
Multi-Label-Fashion-MNIST-master/4598.png
[0, 1, 0, 0, 0, 0, 1, 1, 0, 0]
[0 1 0 0 0 0 1 1 0 

[1, 0, 0, 0, 1, 0, 1, 0, 0, 0]
[1 0 0 0 1 0 1 0 0 0]
Multi-Label-Fashion-MNIST-master/4754.png
[1, 0, 1, 0, 0, 1, 0, 0, 0, 1]
[1 0 1 0 0 1 0 0 0 1]
Multi-Label-Fashion-MNIST-master/4755.png
[0, 1, 0, 0, 1, 0, 0, 1, 0, 1]
[0 1 0 0 1 0 0 1 0 1]
Multi-Label-Fashion-MNIST-master/4756.png
[0, 0, 1, 0, 0, 0, 1, 0, 0, 0]
[0 0 1 0 0 0 1 0 0 0]
Multi-Label-Fashion-MNIST-master/4757.png
[1, 1, 0, 0, 0, 1, 0, 1, 0, 0]
[1 1 0 0 0 1 0 1 0 0]
Multi-Label-Fashion-MNIST-master/4758.png
[0, 0, 1, 0, 1, 1, 0, 0, 0, 0]
[0 0 1 0 1 1 0 0 0 0]
Multi-Label-Fashion-MNIST-master/4759.png
[0, 0, 1, 1, 0, 0, 0, 1, 1, 0]
[0 0 1 1 0 0 0 1 1 0]
Multi-Label-Fashion-MNIST-master/4760.png
[0, 0, 0, 1, 1, 0, 0, 0, 1, 0]
[0 0 0 1 1 0 0 0 1 0]
Multi-Label-Fashion-MNIST-master/4761.png
[0, 0, 1, 0, 0, 0, 0, 0, 1, 0]
[0 0 1 0 0 0 0 0 1 0]
Multi-Label-Fashion-MNIST-master/4762.png
[1, 0, 0, 0, 1, 0, 0, 1, 1, 0]
[1 0 0 0 1 0 0 1 1 0]
Multi-Label-Fashion-MNIST-master/4763.png
[0, 0, 0, 0, 0, 1, 0, 1, 0, 1]
[0 0 0 0 0 1 0 1 0 

[1, 1, 0, 0, 0, 0, 0, 0, 1, 1]
[1 1 0 0 0 0 0 0 1 1]
Multi-Label-Fashion-MNIST-master/4918.png
[1, 0, 0, 0, 0, 1, 0, 1, 0, 0]
[1 0 0 0 0 1 0 1 0 0]
Multi-Label-Fashion-MNIST-master/4919.png
[0, 0, 1, 0, 0, 1, 0, 0, 1, 1]
[0 0 1 0 0 1 0 0 1 1]
Multi-Label-Fashion-MNIST-master/4920.png
[1, 0, 0, 1, 0, 1, 0, 0, 0, 1]
[1 0 0 1 0 1 0 0 0 1]
Multi-Label-Fashion-MNIST-master/4921.png
[0, 1, 1, 0, 0, 1, 0, 0, 1, 0]
[0 1 1 0 0 1 0 0 1 0]
Multi-Label-Fashion-MNIST-master/4922.png
[0, 0, 1, 0, 0, 0, 0, 1, 1, 0]
[0 0 1 0 0 0 0 1 1 0]
Multi-Label-Fashion-MNIST-master/4923.png
[0, 1, 1, 0, 0, 1, 1, 0, 0, 0]
[0 1 1 0 0 1 1 0 0 0]
Multi-Label-Fashion-MNIST-master/4924.png
[1, 0, 0, 0, 0, 1, 0, 0, 0, 0]
[1 0 0 0 0 1 0 0 0 0]
Multi-Label-Fashion-MNIST-master/4925.png
[1, 0, 0, 0, 0, 0, 1, 0, 1, 1]
[1 0 0 0 0 0 1 0 1 1]
Multi-Label-Fashion-MNIST-master/4926.png
[1, 0, 0, 0, 1, 0, 0, 1, 0, 0]
[1 0 0 0 1 0 0 1 0 0]
Multi-Label-Fashion-MNIST-master/4927.png
[0, 1, 1, 0, 0, 0, 0, 0, 1, 1]
[0 1 1 0 0 0 0 0 1 

[0, 0, 1, 0, 0, 1, 1, 0, 0, 1]
[0 0 1 0 0 1 1 0 0 1]
Multi-Label-Fashion-MNIST-master/5083.png
[1, 1, 0, 1, 0, 0, 0, 0, 1, 0]
[1 1 0 1 0 0 0 0 1 0]
Multi-Label-Fashion-MNIST-master/5084.png
[0, 0, 0, 0, 0, 1, 1, 0, 0, 0]
[0 0 0 0 0 1 1 0 0 0]
Multi-Label-Fashion-MNIST-master/5085.png
[1, 0, 0, 1, 0, 0, 1, 0, 0, 0]
[1 0 0 1 0 0 1 0 0 0]
Multi-Label-Fashion-MNIST-master/5086.png
[0, 0, 0, 0, 1, 0, 1, 0, 1, 0]
[0 0 0 0 1 0 1 0 1 0]
Multi-Label-Fashion-MNIST-master/5087.png
[1, 1, 0, 0, 0, 0, 0, 1, 0, 0]
[1 1 0 0 0 0 0 1 0 0]
Multi-Label-Fashion-MNIST-master/5088.png
[1, 0, 0, 0, 1, 0, 0, 1, 0, 0]
[1 0 0 0 1 0 0 1 0 0]
Multi-Label-Fashion-MNIST-master/5089.png
[0, 0, 1, 0, 1, 0, 1, 0, 0, 0]
[0 0 1 0 1 0 1 0 0 0]
Multi-Label-Fashion-MNIST-master/5090.png
[1, 1, 0, 0, 0, 1, 0, 0, 0, 0]
[1 1 0 0 0 1 0 0 0 0]
Multi-Label-Fashion-MNIST-master/5091.png
[0, 0, 1, 1, 0, 1, 0, 0, 1, 0]
[0 0 1 1 0 1 0 0 1 0]
Multi-Label-Fashion-MNIST-master/5092.png
[1, 0, 1, 0, 0, 0, 1, 1, 0, 0]
[1 0 1 0 0 0 1 1 0 

[0, 0, 0, 0, 0, 0, 0, 1, 1, 1]
[0 0 0 0 0 0 0 1 1 1]
Multi-Label-Fashion-MNIST-master/5238.png
[0, 0, 1, 1, 0, 0, 0, 1, 0, 0]
[0 0 1 1 0 0 0 1 0 0]
Multi-Label-Fashion-MNIST-master/5239.png
[1, 1, 0, 0, 0, 0, 0, 1, 0, 1]
[1 1 0 0 0 0 0 1 0 1]
Multi-Label-Fashion-MNIST-master/5240.png
[0, 0, 1, 1, 1, 0, 0, 0, 1, 0]
[0 0 1 1 1 0 0 0 1 0]
Multi-Label-Fashion-MNIST-master/5241.png
[0, 1, 0, 0, 0, 0, 1, 1, 0, 0]
[0 1 0 0 0 0 1 1 0 0]
Multi-Label-Fashion-MNIST-master/5242.png
[0, 0, 1, 0, 0, 1, 0, 1, 0, 0]
[0 0 1 0 0 1 0 1 0 0]
Multi-Label-Fashion-MNIST-master/5243.png
[0, 1, 0, 0, 1, 1, 1, 0, 0, 0]
[0 1 0 0 1 1 1 0 0 0]
Multi-Label-Fashion-MNIST-master/5244.png
[0, 1, 0, 0, 1, 0, 1, 0, 0, 1]
[0 1 0 0 1 0 1 0 0 1]
Multi-Label-Fashion-MNIST-master/5245.png
[0, 0, 0, 0, 0, 1, 1, 0, 1, 0]
[0 0 0 0 0 1 1 0 1 0]
Multi-Label-Fashion-MNIST-master/5246.png
[1, 0, 0, 0, 0, 0, 1, 1, 1, 0]
[1 0 0 0 0 0 1 1 1 0]
Multi-Label-Fashion-MNIST-master/5247.png
[0, 0, 1, 0, 0, 0, 0, 0, 1, 1]
[0 0 1 0 0 0 0 0 1 

[0, 1, 0, 0, 1, 0, 0, 1, 0, 0]
[0 1 0 0 1 0 0 1 0 0]
Multi-Label-Fashion-MNIST-master/5367.png
[0, 0, 0, 0, 0, 0, 1, 1, 0, 1]
[0 0 0 0 0 0 1 1 0 1]
Multi-Label-Fashion-MNIST-master/5368.png
[0, 1, 0, 0, 0, 1, 0, 0, 0, 1]
[0 1 0 0 0 1 0 0 0 1]
Multi-Label-Fashion-MNIST-master/5369.png
[0, 1, 0, 0, 1, 0, 0, 0, 1, 1]
[0 1 0 0 1 0 0 0 1 1]
Multi-Label-Fashion-MNIST-master/5370.png
[1, 0, 0, 1, 1, 0, 0, 0, 0, 0]
[1 0 0 1 1 0 0 0 0 0]
Multi-Label-Fashion-MNIST-master/5371.png
[1, 0, 1, 0, 1, 0, 0, 0, 0, 0]
[1 0 1 0 1 0 0 0 0 0]
Multi-Label-Fashion-MNIST-master/5372.png
[1, 1, 0, 1, 0, 0, 0, 0, 0, 0]
[1 1 0 1 0 0 0 0 0 0]
Multi-Label-Fashion-MNIST-master/5373.png
[1, 0, 0, 1, 1, 0, 0, 0, 0, 1]
[1 0 0 1 1 0 0 0 0 1]
Multi-Label-Fashion-MNIST-master/5374.png
[0, 1, 0, 1, 0, 0, 1, 1, 0, 0]
[0 1 0 1 0 0 1 1 0 0]
Multi-Label-Fashion-MNIST-master/5375.png
[0, 0, 0, 0, 1, 0, 0, 1, 1, 0]
[0 0 0 0 1 0 0 1 1 0]
Multi-Label-Fashion-MNIST-master/5376.png
[1, 0, 0, 0, 0, 0, 1, 0, 1, 1]
[1 0 0 0 0 0 1 0 1 

[0, 1, 1, 0, 0, 0, 0, 1, 0, 1]
[0 1 1 0 0 0 0 1 0 1]
Multi-Label-Fashion-MNIST-master/5509.png
[0, 0, 0, 1, 1, 0, 1, 0, 0, 0]
[0 0 0 1 1 0 1 0 0 0]
Multi-Label-Fashion-MNIST-master/5510.png
[0, 0, 0, 1, 0, 0, 1, 1, 1, 0]
[0 0 0 1 0 0 1 1 1 0]
Multi-Label-Fashion-MNIST-master/5511.png
[0, 1, 1, 0, 1, 0, 0, 0, 0, 1]
[0 1 1 0 1 0 0 0 0 1]
Multi-Label-Fashion-MNIST-master/5512.png
[0, 0, 0, 1, 0, 0, 0, 0, 1, 1]
[0 0 0 1 0 0 0 0 1 1]
Multi-Label-Fashion-MNIST-master/5513.png
[0, 1, 1, 0, 0, 1, 0, 0, 0, 0]
[0 1 1 0 0 1 0 0 0 0]
Multi-Label-Fashion-MNIST-master/5514.png
[0, 1, 0, 1, 0, 0, 1, 1, 0, 0]
[0 1 0 1 0 0 1 1 0 0]
Multi-Label-Fashion-MNIST-master/5515.png
[1, 1, 0, 0, 0, 0, 0, 0, 1, 0]
[1 1 0 0 0 0 0 0 1 0]
Multi-Label-Fashion-MNIST-master/5516.png
[1, 0, 0, 0, 0, 1, 0, 0, 1, 0]
[1 0 0 0 0 1 0 0 1 0]
Multi-Label-Fashion-MNIST-master/5517.png
[1, 0, 0, 0, 1, 0, 0, 0, 1, 0]
[1 0 0 0 1 0 0 0 1 0]
Multi-Label-Fashion-MNIST-master/5518.png
[0, 1, 0, 1, 0, 0, 1, 0, 0, 0]
[0 1 0 1 0 0 1 0 0 

[0, 0, 1, 0, 0, 0, 0, 0, 0, 0]
[0 0 1 0 0 0 0 0 0 0]
Multi-Label-Fashion-MNIST-master/5647.png
[0, 0, 0, 0, 1, 0, 1, 0, 1, 1]
[0 0 0 0 1 0 1 0 1 1]
Multi-Label-Fashion-MNIST-master/5648.png
[0, 0, 0, 1, 0, 1, 1, 0, 1, 0]
[0 0 0 1 0 1 1 0 1 0]
Multi-Label-Fashion-MNIST-master/5649.png
[1, 0, 1, 1, 1, 0, 0, 0, 0, 0]
[1 0 1 1 1 0 0 0 0 0]
Multi-Label-Fashion-MNIST-master/5650.png
[0, 1, 1, 0, 0, 1, 0, 1, 0, 0]
[0 1 1 0 0 1 0 1 0 0]
Multi-Label-Fashion-MNIST-master/5651.png
[1, 0, 0, 1, 0, 0, 0, 1, 0, 1]
[1 0 0 1 0 0 0 1 0 1]
Multi-Label-Fashion-MNIST-master/5652.png
[1, 1, 0, 0, 0, 0, 0, 1, 1, 0]
[1 1 0 0 0 0 0 1 1 0]
Multi-Label-Fashion-MNIST-master/5653.png
[1, 0, 0, 0, 1, 1, 0, 1, 0, 0]
[1 0 0 0 1 1 0 1 0 0]
Multi-Label-Fashion-MNIST-master/5654.png
[1, 0, 0, 0, 1, 1, 0, 0, 0, 0]
[1 0 0 0 1 1 0 0 0 0]
Multi-Label-Fashion-MNIST-master/5655.png
[1, 0, 0, 0, 0, 0, 0, 1, 1, 0]
[1 0 0 0 0 0 0 1 1 0]
Multi-Label-Fashion-MNIST-master/5656.png
[0, 0, 0, 0, 0, 0, 1, 1, 1, 0]
[0 0 0 0 0 0 1 1 1 

[0, 1, 0, 1, 0, 0, 1, 0, 1, 0]
[0 1 0 1 0 0 1 0 1 0]
Multi-Label-Fashion-MNIST-master/5789.png
[0, 1, 1, 0, 0, 1, 0, 0, 0, 0]
[0 1 1 0 0 1 0 0 0 0]
Multi-Label-Fashion-MNIST-master/5790.png
[0, 0, 0, 0, 1, 0, 1, 0, 1, 1]
[0 0 0 0 1 0 1 0 1 1]
Multi-Label-Fashion-MNIST-master/5791.png
[0, 0, 0, 0, 0, 1, 1, 0, 1, 0]
[0 0 0 0 0 1 1 0 1 0]
Multi-Label-Fashion-MNIST-master/5792.png
[0, 0, 1, 0, 0, 1, 0, 0, 0, 1]
[0 0 1 0 0 1 0 0 0 1]
Multi-Label-Fashion-MNIST-master/5793.png
[0, 0, 1, 1, 0, 0, 0, 0, 0, 1]
[0 0 1 1 0 0 0 0 0 1]
Multi-Label-Fashion-MNIST-master/5794.png
[0, 0, 0, 0, 0, 0, 1, 0, 1, 0]
[0 0 0 0 0 0 1 0 1 0]
Multi-Label-Fashion-MNIST-master/5795.png
[1, 0, 0, 1, 0, 1, 0, 1, 0, 0]
[1 0 0 1 0 1 0 1 0 0]
Multi-Label-Fashion-MNIST-master/5796.png
[0, 1, 0, 0, 0, 1, 1, 0, 1, 0]
[0 1 0 0 0 1 1 0 1 0]
Multi-Label-Fashion-MNIST-master/5797.png
[0, 0, 1, 1, 0, 0, 0, 0, 0, 1]
[0 0 1 1 0 0 0 0 0 1]
Multi-Label-Fashion-MNIST-master/5798.png
[0, 1, 0, 1, 0, 1, 0, 1, 0, 0]
[0 1 0 1 0 1 0 1 0 

[1, 0, 1, 0, 0, 0, 1, 1, 0, 0]
[1 0 1 0 0 0 1 1 0 0]
Multi-Label-Fashion-MNIST-master/5945.png
[1, 0, 1, 1, 0, 1, 0, 0, 0, 0]
[1 0 1 1 0 1 0 0 0 0]
Multi-Label-Fashion-MNIST-master/5946.png
[1, 0, 0, 1, 0, 0, 0, 1, 0, 0]
[1 0 0 1 0 0 0 1 0 0]
Multi-Label-Fashion-MNIST-master/5947.png
[1, 0, 1, 0, 0, 0, 1, 0, 1, 0]
[1 0 1 0 0 0 1 0 1 0]
Multi-Label-Fashion-MNIST-master/5948.png
[1, 0, 1, 0, 0, 0, 0, 0, 0, 1]
[1 0 1 0 0 0 0 0 0 1]
Multi-Label-Fashion-MNIST-master/5949.png
[0, 0, 1, 1, 0, 1, 0, 1, 0, 0]
[0 0 1 1 0 1 0 1 0 0]
Multi-Label-Fashion-MNIST-master/5950.png
[0, 1, 1, 0, 1, 0, 0, 0, 0, 0]
[0 1 1 0 1 0 0 0 0 0]
Multi-Label-Fashion-MNIST-master/5951.png
[0, 1, 0, 0, 0, 1, 0, 0, 1, 0]
[0 1 0 0 0 1 0 0 1 0]
Multi-Label-Fashion-MNIST-master/5952.png
[0, 1, 1, 0, 0, 1, 0, 0, 0, 0]
[0 1 1 0 0 1 0 0 0 0]
Multi-Label-Fashion-MNIST-master/5953.png
[0, 1, 0, 0, 1, 0, 0, 1, 0, 1]
[0 1 0 0 1 0 0 1 0 1]
Multi-Label-Fashion-MNIST-master/5954.png
[0, 0, 1, 0, 1, 0, 0, 0, 1, 1]
[0 0 1 0 1 0 0 0 1 

[0, 1, 0, 0, 1, 0, 0, 0, 0, 1]
[0 1 0 0 1 0 0 0 0 1]
Multi-Label-Fashion-MNIST-master/6084.png
[1, 0, 1, 0, 0, 0, 0, 0, 1, 0]
[1 0 1 0 0 0 0 0 1 0]
Multi-Label-Fashion-MNIST-master/6085.png
[0, 0, 0, 1, 0, 0, 1, 0, 1, 1]
[0 0 0 1 0 0 1 0 1 1]
Multi-Label-Fashion-MNIST-master/6086.png
[0, 1, 1, 0, 1, 0, 0, 1, 0, 0]
[0 1 1 0 1 0 0 1 0 0]
Multi-Label-Fashion-MNIST-master/6087.png
[0, 1, 0, 1, 0, 0, 1, 0, 0, 1]
[0 1 0 1 0 0 1 0 0 1]
Multi-Label-Fashion-MNIST-master/6088.png
[0, 1, 0, 1, 0, 0, 0, 0, 1, 0]
[0 1 0 1 0 0 0 0 1 0]
Multi-Label-Fashion-MNIST-master/6089.png
[1, 0, 1, 0, 0, 0, 0, 0, 1, 0]
[1 0 1 0 0 0 0 0 1 0]
Multi-Label-Fashion-MNIST-master/6090.png
[1, 1, 0, 0, 0, 0, 0, 1, 1, 0]
[1 1 0 0 0 0 0 1 1 0]
Multi-Label-Fashion-MNIST-master/6091.png
[0, 1, 1, 0, 0, 0, 1, 0, 0, 0]
[0 1 1 0 0 0 1 0 0 0]
Multi-Label-Fashion-MNIST-master/6092.png
[0, 1, 1, 1, 0, 0, 0, 1, 0, 0]
[0 1 1 1 0 0 0 1 0 0]
Multi-Label-Fashion-MNIST-master/6093.png
[0, 0, 0, 1, 0, 1, 1, 0, 0, 0]
[0 0 0 1 0 1 1 0 0 

[1, 0, 0, 0, 0, 0, 1, 1, 0, 0]
[1 0 0 0 0 0 1 1 0 0]
Multi-Label-Fashion-MNIST-master/6248.png
[0, 0, 0, 1, 1, 1, 0, 1, 0, 0]
[0 0 0 1 1 1 0 1 0 0]
Multi-Label-Fashion-MNIST-master/6249.png
[1, 1, 1, 0, 0, 0, 0, 0, 0, 0]
[1 1 1 0 0 0 0 0 0 0]
Multi-Label-Fashion-MNIST-master/6250.png
[1, 0, 1, 0, 0, 0, 0, 0, 0, 1]
[1 0 1 0 0 0 0 0 0 1]
Multi-Label-Fashion-MNIST-master/6251.png
[0, 0, 0, 0, 0, 0, 1, 0, 1, 1]
[0 0 0 0 0 0 1 0 1 1]
Multi-Label-Fashion-MNIST-master/6252.png
[1, 0, 1, 0, 0, 0, 1, 0, 0, 0]
[1 0 1 0 0 0 1 0 0 0]
Multi-Label-Fashion-MNIST-master/6253.png
[0, 0, 0, 0, 0, 1, 0, 1, 1, 0]
[0 0 0 0 0 1 0 1 1 0]
Multi-Label-Fashion-MNIST-master/6254.png
[0, 0, 0, 1, 1, 0, 0, 1, 0, 0]
[0 0 0 1 1 0 0 1 0 0]
Multi-Label-Fashion-MNIST-master/6255.png
[0, 0, 1, 0, 0, 0, 1, 0, 1, 1]
[0 0 1 0 0 0 1 0 1 1]
Multi-Label-Fashion-MNIST-master/6256.png
[1, 0, 0, 0, 1, 0, 0, 1, 1, 0]
[1 0 0 0 1 0 0 1 1 0]
Multi-Label-Fashion-MNIST-master/6257.png
[1, 1, 0, 0, 0, 1, 0, 0, 1, 0]
[1 1 0 0 0 1 0 0 1 

[0, 1, 0, 0, 0, 0, 0, 1, 0, 1]
[0 1 0 0 0 0 0 1 0 1]
Multi-Label-Fashion-MNIST-master/6414.png
[1, 1, 1, 1, 0, 0, 0, 0, 0, 0]
[1 1 1 1 0 0 0 0 0 0]
Multi-Label-Fashion-MNIST-master/6415.png
[0, 0, 0, 0, 0, 1, 1, 0, 1, 1]
[0 0 0 0 0 1 1 0 1 1]
Multi-Label-Fashion-MNIST-master/6416.png
[1, 0, 0, 0, 0, 0, 0, 0, 1, 0]
[1 0 0 0 0 0 0 0 1 0]
Multi-Label-Fashion-MNIST-master/6417.png
[0, 0, 0, 1, 0, 1, 0, 0, 0, 1]
[0 0 0 1 0 1 0 0 0 1]
Multi-Label-Fashion-MNIST-master/6418.png
[0, 0, 0, 0, 0, 0, 0, 1, 1, 1]
[0 0 0 0 0 0 0 1 1 1]
Multi-Label-Fashion-MNIST-master/6419.png
[1, 0, 0, 0, 0, 1, 1, 0, 0, 0]
[1 0 0 0 0 1 1 0 0 0]
Multi-Label-Fashion-MNIST-master/6420.png
[0, 1, 0, 0, 0, 0, 1, 1, 0, 1]
[0 1 0 0 0 0 1 1 0 1]
Multi-Label-Fashion-MNIST-master/6421.png
[0, 1, 0, 0, 0, 1, 1, 0, 0, 0]
[0 1 0 0 0 1 1 0 0 0]
Multi-Label-Fashion-MNIST-master/6422.png
[0, 0, 1, 1, 0, 1, 0, 0, 0, 1]
[0 0 1 1 0 1 0 0 0 1]
Multi-Label-Fashion-MNIST-master/6423.png
[0, 1, 0, 1, 1, 0, 0, 1, 0, 0]
[0 1 0 1 1 0 0 1 0 

[0, 1, 0, 1, 0, 1, 0, 0, 0, 0]
[0 1 0 1 0 1 0 0 0 0]
Multi-Label-Fashion-MNIST-master/6564.png
[0, 0, 0, 1, 1, 0, 0, 1, 0, 0]
[0 0 0 1 1 0 0 1 0 0]
Multi-Label-Fashion-MNIST-master/6565.png
[0, 0, 0, 0, 1, 1, 1, 0, 0, 0]
[0 0 0 0 1 1 1 0 0 0]
Multi-Label-Fashion-MNIST-master/6566.png
[1, 1, 0, 0, 0, 0, 0, 0, 1, 0]
[1 1 0 0 0 0 0 0 1 0]
Multi-Label-Fashion-MNIST-master/6567.png
[0, 0, 0, 0, 1, 0, 1, 0, 1, 0]
[0 0 0 0 1 0 1 0 1 0]
Multi-Label-Fashion-MNIST-master/6568.png
[1, 0, 0, 0, 0, 0, 1, 1, 1, 0]
[1 0 0 0 0 0 1 1 1 0]
Multi-Label-Fashion-MNIST-master/6569.png
[1, 1, 1, 0, 0, 0, 0, 0, 0, 1]
[1 1 1 0 0 0 0 0 0 1]
Multi-Label-Fashion-MNIST-master/6570.png
[1, 1, 0, 0, 1, 0, 0, 0, 0, 0]
[1 1 0 0 1 0 0 0 0 0]
Multi-Label-Fashion-MNIST-master/6571.png
[0, 1, 0, 0, 1, 1, 0, 0, 1, 0]
[0 1 0 0 1 1 0 0 1 0]
Multi-Label-Fashion-MNIST-master/6572.png
[0, 0, 0, 0, 1, 1, 1, 0, 1, 0]
[0 0 0 0 1 1 1 0 1 0]
Multi-Label-Fashion-MNIST-master/6573.png
[0, 1, 0, 0, 1, 0, 1, 1, 0, 0]
[0 1 0 0 1 0 1 1 0 

[0, 1, 0, 0, 0, 0, 0, 1, 1, 0]
[0 1 0 0 0 0 0 1 1 0]
Multi-Label-Fashion-MNIST-master/6707.png
[0, 0, 1, 0, 0, 0, 0, 1, 1, 0]
[0 0 1 0 0 0 0 1 1 0]
Multi-Label-Fashion-MNIST-master/6708.png
[1, 1, 0, 0, 0, 0, 0, 0, 0, 1]
[1 1 0 0 0 0 0 0 0 1]
Multi-Label-Fashion-MNIST-master/6709.png
[1, 1, 1, 0, 0, 0, 0, 1, 0, 0]
[1 1 1 0 0 0 0 1 0 0]
Multi-Label-Fashion-MNIST-master/6710.png
[0, 0, 0, 0, 0, 1, 0, 0, 1, 1]
[0 0 0 0 0 1 0 0 1 1]
Multi-Label-Fashion-MNIST-master/6711.png
[0, 0, 0, 0, 1, 1, 0, 0, 1, 0]
[0 0 0 0 1 1 0 0 1 0]
Multi-Label-Fashion-MNIST-master/6712.png
[0, 0, 0, 0, 0, 0, 1, 0, 1, 1]
[0 0 0 0 0 0 1 0 1 1]
Multi-Label-Fashion-MNIST-master/6713.png
[0, 0, 1, 0, 0, 0, 1, 1, 0, 0]
[0 0 1 0 0 0 1 1 0 0]
Multi-Label-Fashion-MNIST-master/6714.png
[0, 0, 0, 1, 0, 1, 1, 0, 0, 1]
[0 0 0 1 0 1 1 0 0 1]
Multi-Label-Fashion-MNIST-master/6715.png
[1, 1, 0, 0, 1, 0, 0, 0, 1, 0]
[1 1 0 0 1 0 0 0 1 0]
Multi-Label-Fashion-MNIST-master/6716.png
[0, 0, 0, 1, 0, 1, 0, 1, 1, 0]
[0 0 0 1 0 1 0 1 1 

[1, 0, 0, 0, 1, 1, 0, 0, 1, 0]
[1 0 0 0 1 1 0 0 1 0]
Multi-Label-Fashion-MNIST-master/6855.png
[1, 1, 0, 0, 1, 0, 0, 0, 0, 1]
[1 1 0 0 1 0 0 0 0 1]
Multi-Label-Fashion-MNIST-master/6856.png
[0, 0, 0, 0, 0, 1, 0, 1, 1, 1]
[0 0 0 0 0 1 0 1 1 1]
Multi-Label-Fashion-MNIST-master/6857.png
[1, 0, 0, 0, 0, 1, 1, 1, 0, 0]
[1 0 0 0 0 1 1 1 0 0]
Multi-Label-Fashion-MNIST-master/6858.png
[0, 0, 0, 0, 1, 1, 0, 1, 0, 1]
[0 0 0 0 1 1 0 1 0 1]
Multi-Label-Fashion-MNIST-master/6859.png
[0, 0, 0, 0, 0, 0, 1, 1, 0, 0]
[0 0 0 0 0 0 1 1 0 0]
Multi-Label-Fashion-MNIST-master/6860.png
[1, 0, 0, 0, 1, 1, 0, 0, 0, 1]
[1 0 0 0 1 1 0 0 0 1]
Multi-Label-Fashion-MNIST-master/6861.png
[0, 0, 0, 1, 1, 0, 0, 1, 0, 1]
[0 0 0 1 1 0 0 1 0 1]
Multi-Label-Fashion-MNIST-master/6862.png
[1, 0, 0, 0, 0, 0, 0, 0, 1, 1]
[1 0 0 0 0 0 0 0 1 1]
Multi-Label-Fashion-MNIST-master/6863.png
[0, 0, 1, 0, 1, 0, 1, 0, 0, 1]
[0 0 1 0 1 0 1 0 0 1]
Multi-Label-Fashion-MNIST-master/6864.png
[1, 0, 0, 0, 1, 1, 0, 0, 0, 1]
[1 0 0 0 1 1 0 0 0 

[0, 0, 0, 1, 0, 0, 1, 1, 1, 0]
[0 0 0 1 0 0 1 1 1 0]
Multi-Label-Fashion-MNIST-master/7006.png
[1, 0, 0, 0, 1, 0, 0, 0, 0, 1]
[1 0 0 0 1 0 0 0 0 1]
Multi-Label-Fashion-MNIST-master/7007.png
[1, 0, 0, 0, 1, 1, 0, 0, 0, 0]
[1 0 0 0 1 1 0 0 0 0]
Multi-Label-Fashion-MNIST-master/7008.png
[1, 0, 0, 0, 0, 0, 1, 0, 0, 0]
[1 0 0 0 0 0 1 0 0 0]
Multi-Label-Fashion-MNIST-master/7009.png
[1, 1, 0, 0, 0, 0, 1, 1, 0, 0]
[1 1 0 0 0 0 1 1 0 0]
Multi-Label-Fashion-MNIST-master/7010.png
[0, 1, 0, 0, 0, 0, 0, 0, 1, 1]
[0 1 0 0 0 0 0 0 1 1]
Multi-Label-Fashion-MNIST-master/7011.png
[1, 1, 0, 0, 1, 0, 0, 0, 1, 0]
[1 1 0 0 1 0 0 0 1 0]
Multi-Label-Fashion-MNIST-master/7012.png
[0, 0, 0, 0, 0, 1, 0, 1, 1, 1]
[0 0 0 0 0 1 0 1 1 1]
Multi-Label-Fashion-MNIST-master/7013.png
[0, 0, 1, 0, 0, 0, 1, 1, 0, 0]
[0 0 1 0 0 0 1 1 0 0]
Multi-Label-Fashion-MNIST-master/7014.png
[0, 0, 0, 1, 0, 0, 1, 1, 0, 0]
[0 0 0 1 0 0 1 1 0 0]
Multi-Label-Fashion-MNIST-master/7015.png
[0, 0, 0, 1, 1, 0, 1, 0, 0, 0]
[0 0 0 1 1 0 1 0 0 

[0, 1, 1, 1, 1, 0, 0, 0, 0, 0]
[0 1 1 1 1 0 0 0 0 0]
Multi-Label-Fashion-MNIST-master/7159.png
[1, 0, 0, 1, 0, 0, 1, 0, 1, 0]
[1 0 0 1 0 0 1 0 1 0]
Multi-Label-Fashion-MNIST-master/7160.png
[0, 1, 0, 0, 1, 1, 0, 0, 0, 0]
[0 1 0 0 1 1 0 0 0 0]
Multi-Label-Fashion-MNIST-master/7161.png
[0, 0, 1, 0, 0, 1, 0, 1, 0, 1]
[0 0 1 0 0 1 0 1 0 1]
Multi-Label-Fashion-MNIST-master/7162.png
[0, 0, 1, 1, 0, 0, 1, 0, 0, 0]
[0 0 1 1 0 0 1 0 0 0]
Multi-Label-Fashion-MNIST-master/7163.png
[1, 0, 1, 0, 0, 0, 0, 1, 0, 1]
[1 0 1 0 0 0 0 1 0 1]
Multi-Label-Fashion-MNIST-master/7164.png
[0, 0, 1, 0, 0, 0, 0, 1, 0, 0]
[0 0 1 0 0 0 0 1 0 0]
Multi-Label-Fashion-MNIST-master/7165.png
[0, 0, 0, 0, 0, 1, 0, 1, 0, 1]
[0 0 0 0 0 1 0 1 0 1]
Multi-Label-Fashion-MNIST-master/7166.png
[1, 0, 1, 0, 0, 1, 0, 0, 1, 0]
[1 0 1 0 0 1 0 0 1 0]
Multi-Label-Fashion-MNIST-master/7167.png
[0, 1, 1, 1, 0, 0, 0, 1, 0, 0]
[0 1 1 1 0 0 0 1 0 0]
Multi-Label-Fashion-MNIST-master/7168.png
[0, 0, 0, 0, 1, 0, 1, 0, 0, 1]
[0 0 0 0 1 0 1 0 0 

[1, 0, 0, 1, 1, 0, 0, 1, 0, 0]
[1 0 0 1 1 0 0 1 0 0]
Multi-Label-Fashion-MNIST-master/7312.png
[0, 0, 0, 1, 1, 0, 0, 0, 0, 1]
[0 0 0 1 1 0 0 0 0 1]
Multi-Label-Fashion-MNIST-master/7313.png
[0, 1, 0, 0, 0, 0, 0, 1, 0, 1]
[0 1 0 0 0 0 0 1 0 1]
Multi-Label-Fashion-MNIST-master/7314.png
[0, 0, 1, 0, 0, 0, 0, 0, 0, 1]
[0 0 1 0 0 0 0 0 0 1]
Multi-Label-Fashion-MNIST-master/7315.png
[0, 1, 1, 0, 1, 0, 0, 1, 0, 0]
[0 1 1 0 1 0 0 1 0 0]
Multi-Label-Fashion-MNIST-master/7316.png
[1, 1, 0, 1, 0, 0, 0, 0, 1, 0]
[1 1 0 1 0 0 0 0 1 0]
Multi-Label-Fashion-MNIST-master/7317.png
[0, 0, 1, 1, 1, 0, 0, 0, 0, 0]
[0 0 1 1 1 0 0 0 0 0]
Multi-Label-Fashion-MNIST-master/7318.png
[0, 0, 0, 1, 1, 0, 0, 0, 0, 1]
[0 0 0 1 1 0 0 0 0 1]
Multi-Label-Fashion-MNIST-master/7319.png
[1, 1, 1, 0, 0, 0, 0, 1, 0, 0]
[1 1 1 0 0 0 0 1 0 0]
Multi-Label-Fashion-MNIST-master/7320.png
[0, 0, 1, 0, 0, 0, 0, 1, 0, 1]
[0 0 1 0 0 0 0 1 0 1]
Multi-Label-Fashion-MNIST-master/7321.png
[0, 1, 0, 0, 1, 0, 0, 1, 0, 1]
[0 1 0 0 1 0 0 1 0 

[0, 0, 1, 0, 1, 1, 0, 0, 0, 1]
[0 0 1 0 1 1 0 0 0 1]
Multi-Label-Fashion-MNIST-master/7472.png
[1, 0, 0, 0, 1, 0, 0, 0, 1, 1]
[1 0 0 0 1 0 0 0 1 1]
Multi-Label-Fashion-MNIST-master/7473.png
[1, 0, 0, 0, 0, 0, 0, 1, 0, 0]
[1 0 0 0 0 0 0 1 0 0]
Multi-Label-Fashion-MNIST-master/7474.png
[1, 0, 1, 0, 0, 0, 0, 1, 0, 0]
[1 0 1 0 0 0 0 1 0 0]
Multi-Label-Fashion-MNIST-master/7475.png
[1, 1, 0, 0, 0, 0, 1, 0, 1, 0]
[1 1 0 0 0 0 1 0 1 0]
Multi-Label-Fashion-MNIST-master/7476.png
[0, 1, 0, 0, 0, 0, 1, 1, 1, 0]
[0 1 0 0 0 0 1 1 1 0]
Multi-Label-Fashion-MNIST-master/7477.png
[1, 0, 0, 0, 1, 0, 0, 1, 1, 0]
[1 0 0 0 1 0 0 1 1 0]
Multi-Label-Fashion-MNIST-master/7478.png
[1, 0, 0, 1, 0, 1, 0, 0, 0, 0]
[1 0 0 1 0 1 0 0 0 0]
Multi-Label-Fashion-MNIST-master/7479.png
[1, 0, 1, 0, 0, 0, 1, 0, 0, 1]
[1 0 1 0 0 0 1 0 0 1]
Multi-Label-Fashion-MNIST-master/7480.png
[0, 0, 0, 1, 1, 0, 0, 1, 0, 0]
[0 0 0 1 1 0 0 1 0 0]
Multi-Label-Fashion-MNIST-master/7481.png
[0, 0, 0, 0, 0, 1, 1, 1, 0, 0]
[0 0 0 0 0 1 1 1 0 

[1, 0, 0, 1, 0, 0, 1, 0, 0, 0]
[1 0 0 1 0 0 1 0 0 0]
Multi-Label-Fashion-MNIST-master/7628.png
[0, 0, 0, 0, 1, 1, 1, 1, 0, 0]
[0 0 0 0 1 1 1 1 0 0]
Multi-Label-Fashion-MNIST-master/7629.png
[0, 0, 0, 1, 0, 1, 1, 0, 0, 0]
[0 0 0 1 0 1 1 0 0 0]
Multi-Label-Fashion-MNIST-master/7630.png
[1, 1, 0, 0, 0, 0, 0, 1, 0, 0]
[1 1 0 0 0 0 0 1 0 0]
Multi-Label-Fashion-MNIST-master/7631.png
[1, 0, 0, 0, 1, 0, 0, 0, 1, 0]
[1 0 0 0 1 0 0 0 1 0]
Multi-Label-Fashion-MNIST-master/7632.png
[0, 1, 1, 0, 0, 0, 0, 0, 1, 1]
[0 1 1 0 0 0 0 0 1 1]
Multi-Label-Fashion-MNIST-master/7633.png
[0, 0, 0, 1, 1, 0, 0, 1, 0, 1]
[0 0 0 1 1 0 0 1 0 1]
Multi-Label-Fashion-MNIST-master/7634.png
[0, 0, 0, 1, 0, 1, 0, 0, 1, 0]
[0 0 0 1 0 1 0 0 1 0]
Multi-Label-Fashion-MNIST-master/7635.png
[1, 0, 0, 0, 1, 1, 0, 1, 0, 0]
[1 0 0 0 1 1 0 1 0 0]
Multi-Label-Fashion-MNIST-master/7636.png
[0, 0, 0, 0, 1, 1, 0, 0, 1, 0]
[0 0 0 0 1 1 0 0 1 0]
Multi-Label-Fashion-MNIST-master/7637.png
[0, 1, 0, 0, 0, 0, 1, 0, 1, 1]
[0 1 0 0 0 0 1 0 1 

[1, 1, 0, 1, 0, 0, 0, 0, 0, 1]
[1 1 0 1 0 0 0 0 0 1]
Multi-Label-Fashion-MNIST-master/7768.png
[0, 1, 1, 0, 0, 0, 0, 0, 1, 0]
[0 1 1 0 0 0 0 0 1 0]
Multi-Label-Fashion-MNIST-master/7769.png
[1, 0, 1, 0, 1, 1, 0, 0, 0, 0]
[1 0 1 0 1 1 0 0 0 0]
Multi-Label-Fashion-MNIST-master/7770.png
[1, 0, 1, 0, 0, 1, 0, 1, 0, 0]
[1 0 1 0 0 1 0 1 0 0]
Multi-Label-Fashion-MNIST-master/7771.png
[0, 0, 0, 1, 1, 0, 1, 1, 0, 0]
[0 0 0 1 1 0 1 1 0 0]
Multi-Label-Fashion-MNIST-master/7772.png
[0, 0, 1, 0, 1, 0, 1, 1, 0, 0]
[0 0 1 0 1 0 1 1 0 0]
Multi-Label-Fashion-MNIST-master/7773.png
[1, 0, 0, 1, 0, 0, 0, 1, 1, 0]
[1 0 0 1 0 0 0 1 1 0]
Multi-Label-Fashion-MNIST-master/7774.png
[0, 0, 1, 0, 0, 0, 1, 1, 1, 0]
[0 0 1 0 0 0 1 1 1 0]
Multi-Label-Fashion-MNIST-master/7775.png
[0, 1, 0, 1, 0, 0, 1, 0, 1, 0]
[0 1 0 1 0 0 1 0 1 0]
Multi-Label-Fashion-MNIST-master/7776.png
[0, 1, 0, 0, 0, 0, 1, 1, 0, 1]
[0 1 0 0 0 0 1 1 0 1]
Multi-Label-Fashion-MNIST-master/7777.png
[0, 0, 1, 1, 1, 0, 0, 0, 0, 0]
[0 0 1 1 1 0 0 0 0 

[0, 0, 0, 0, 1, 0, 0, 1, 0, 1]
[0 0 0 0 1 0 0 1 0 1]
Multi-Label-Fashion-MNIST-master/7933.png
[0, 0, 1, 0, 0, 0, 0, 1, 0, 1]
[0 0 1 0 0 0 0 1 0 1]
Multi-Label-Fashion-MNIST-master/7934.png
[0, 0, 0, 0, 1, 1, 1, 0, 1, 0]
[0 0 0 0 1 1 1 0 1 0]
Multi-Label-Fashion-MNIST-master/7935.png
[1, 0, 0, 1, 0, 0, 0, 0, 1, 0]
[1 0 0 1 0 0 0 0 1 0]
Multi-Label-Fashion-MNIST-master/7936.png
[0, 0, 0, 1, 0, 1, 1, 1, 0, 0]
[0 0 0 1 0 1 1 1 0 0]
Multi-Label-Fashion-MNIST-master/7937.png
[1, 0, 0, 0, 0, 0, 0, 1, 1, 0]
[1 0 0 0 0 0 0 1 1 0]
Multi-Label-Fashion-MNIST-master/7938.png
[1, 0, 0, 1, 0, 0, 0, 0, 0, 1]
[1 0 0 1 0 0 0 0 0 1]
Multi-Label-Fashion-MNIST-master/7939.png
[1, 0, 0, 1, 1, 1, 0, 0, 0, 0]
[1 0 0 1 1 1 0 0 0 0]
Multi-Label-Fashion-MNIST-master/7940.png
[0, 0, 1, 1, 1, 1, 0, 0, 0, 0]
[0 0 1 1 1 1 0 0 0 0]
Multi-Label-Fashion-MNIST-master/7941.png
[0, 1, 0, 0, 0, 0, 1, 1, 0, 1]
[0 1 0 0 0 0 1 1 0 1]
Multi-Label-Fashion-MNIST-master/7942.png
[1, 0, 0, 0, 0, 1, 0, 0, 1, 0]
[1 0 0 0 0 1 0 0 1 

[1, 0, 0, 0, 1, 0, 0, 1, 0, 0]
[1 0 0 0 1 0 0 1 0 0]
Multi-Label-Fashion-MNIST-master/8104.png
[1, 1, 1, 1, 0, 0, 0, 0, 0, 0]
[1 1 1 1 0 0 0 0 0 0]
Multi-Label-Fashion-MNIST-master/8105.png
[0, 0, 0, 1, 0, 1, 0, 1, 0, 1]
[0 0 0 1 0 1 0 1 0 1]
Multi-Label-Fashion-MNIST-master/8106.png
[1, 0, 0, 0, 0, 1, 1, 0, 0, 0]
[1 0 0 0 0 1 1 0 0 0]
Multi-Label-Fashion-MNIST-master/8107.png
[1, 0, 0, 1, 1, 0, 0, 0, 1, 0]
[1 0 0 1 1 0 0 0 1 0]
Multi-Label-Fashion-MNIST-master/8108.png
[1, 0, 0, 0, 0, 1, 0, 0, 1, 1]
[1 0 0 0 0 1 0 0 1 1]
Multi-Label-Fashion-MNIST-master/8109.png
[1, 1, 0, 1, 0, 0, 0, 0, 0, 1]
[1 1 0 1 0 0 0 0 0 1]
Multi-Label-Fashion-MNIST-master/8110.png
[0, 1, 1, 1, 0, 0, 0, 0, 0, 1]
[0 1 1 1 0 0 0 0 0 1]
Multi-Label-Fashion-MNIST-master/8111.png
[0, 0, 1, 1, 1, 0, 0, 1, 0, 0]
[0 0 1 1 1 0 0 1 0 0]
Multi-Label-Fashion-MNIST-master/8112.png
[0, 0, 1, 0, 0, 1, 0, 0, 0, 0]
[0 0 1 0 0 1 0 0 0 0]
Multi-Label-Fashion-MNIST-master/8113.png
[0, 0, 1, 1, 0, 0, 0, 0, 1, 0]
[0 0 1 1 0 0 0 0 1 

[0, 0, 0, 0, 0, 1, 1, 1, 0, 0]
[0 0 0 0 0 1 1 1 0 0]
Multi-Label-Fashion-MNIST-master/8270.png
[0, 1, 1, 0, 0, 0, 0, 0, 1, 0]
[0 1 1 0 0 0 0 0 1 0]
Multi-Label-Fashion-MNIST-master/8271.png
[0, 1, 0, 1, 0, 1, 0, 0, 0, 1]
[0 1 0 1 0 1 0 0 0 1]
Multi-Label-Fashion-MNIST-master/8272.png
[1, 0, 1, 0, 1, 0, 0, 0, 0, 0]
[1 0 1 0 1 0 0 0 0 0]
Multi-Label-Fashion-MNIST-master/8273.png
[0, 1, 0, 1, 0, 1, 1, 0, 0, 0]
[0 1 0 1 0 1 1 0 0 0]
Multi-Label-Fashion-MNIST-master/8274.png
[0, 0, 1, 0, 0, 1, 0, 0, 1, 0]
[0 0 1 0 0 1 0 0 1 0]
Multi-Label-Fashion-MNIST-master/8275.png
[1, 0, 0, 1, 1, 0, 0, 0, 1, 0]
[1 0 0 1 1 0 0 0 1 0]
Multi-Label-Fashion-MNIST-master/8276.png
[0, 1, 0, 0, 1, 1, 0, 0, 0, 1]
[0 1 0 0 1 1 0 0 0 1]
Multi-Label-Fashion-MNIST-master/8277.png
[1, 0, 0, 1, 0, 0, 0, 0, 1, 0]
[1 0 0 1 0 0 0 0 1 0]
Multi-Label-Fashion-MNIST-master/8278.png
[1, 0, 0, 1, 0, 0, 0, 1, 0, 0]
[1 0 0 1 0 0 0 1 0 0]
Multi-Label-Fashion-MNIST-master/8279.png
[1, 0, 0, 0, 0, 1, 0, 0, 1, 0]
[1 0 0 0 0 1 0 0 1 

[0, 0, 1, 1, 0, 0, 0, 0, 0, 1]
[0 0 1 1 0 0 0 0 0 1]
Multi-Label-Fashion-MNIST-master/8432.png
[0, 0, 1, 0, 0, 0, 1, 0, 1, 0]
[0 0 1 0 0 0 1 0 1 0]
Multi-Label-Fashion-MNIST-master/8433.png
[1, 0, 0, 1, 1, 0, 0, 0, 0, 0]
[1 0 0 1 1 0 0 0 0 0]
Multi-Label-Fashion-MNIST-master/8434.png
[0, 0, 1, 1, 0, 1, 0, 0, 0, 1]
[0 0 1 1 0 1 0 0 0 1]
Multi-Label-Fashion-MNIST-master/8435.png
[1, 0, 1, 0, 0, 0, 0, 0, 1, 0]
[1 0 1 0 0 0 0 0 1 0]
Multi-Label-Fashion-MNIST-master/8436.png
[1, 1, 0, 0, 1, 1, 0, 0, 0, 0]
[1 1 0 0 1 1 0 0 0 0]
Multi-Label-Fashion-MNIST-master/8437.png
[0, 1, 0, 1, 0, 1, 0, 0, 0, 1]
[0 1 0 1 0 1 0 0 0 1]
Multi-Label-Fashion-MNIST-master/8438.png
[0, 1, 1, 0, 1, 0, 0, 0, 0, 0]
[0 1 1 0 1 0 0 0 0 0]
Multi-Label-Fashion-MNIST-master/8439.png
[1, 0, 1, 0, 0, 1, 0, 0, 0, 1]
[1 0 1 0 0 1 0 0 0 1]
Multi-Label-Fashion-MNIST-master/8440.png
[1, 0, 0, 1, 0, 0, 1, 0, 0, 1]
[1 0 0 1 0 0 1 0 0 1]
Multi-Label-Fashion-MNIST-master/8441.png
[1, 1, 0, 0, 0, 0, 0, 0, 1, 0]
[1 1 0 0 0 0 0 0 1 

[0, 0, 1, 1, 1, 0, 0, 0, 0, 0]
[0 0 1 1 1 0 0 0 0 0]
Multi-Label-Fashion-MNIST-master/8599.png
[0, 0, 0, 0, 0, 1, 1, 1, 0, 1]
[0 0 0 0 0 1 1 1 0 1]
Multi-Label-Fashion-MNIST-master/8600.png
[0, 0, 1, 0, 1, 0, 0, 1, 0, 1]
[0 0 1 0 1 0 0 1 0 1]
Multi-Label-Fashion-MNIST-master/8601.png
[1, 0, 0, 1, 1, 0, 0, 1, 0, 0]
[1 0 0 1 1 0 0 1 0 0]
Multi-Label-Fashion-MNIST-master/8602.png
[0, 0, 1, 0, 0, 1, 1, 0, 0, 0]
[0 0 1 0 0 1 1 0 0 0]
Multi-Label-Fashion-MNIST-master/8603.png
[0, 1, 0, 0, 0, 0, 1, 1, 1, 0]
[0 1 0 0 0 0 1 1 1 0]
Multi-Label-Fashion-MNIST-master/8604.png
[0, 0, 0, 1, 0, 0, 0, 1, 0, 1]
[0 0 0 1 0 0 0 1 0 1]
Multi-Label-Fashion-MNIST-master/8605.png
[0, 0, 1, 0, 0, 0, 0, 1, 0, 1]
[0 0 1 0 0 0 0 1 0 1]
Multi-Label-Fashion-MNIST-master/8606.png
[0, 0, 0, 1, 0, 0, 1, 0, 0, 0]
[0 0 0 1 0 0 1 0 0 0]
Multi-Label-Fashion-MNIST-master/8607.png
[0, 0, 1, 1, 0, 0, 0, 0, 1, 0]
[0 0 1 1 0 0 0 0 1 0]
Multi-Label-Fashion-MNIST-master/8608.png
[1, 1, 1, 0, 0, 0, 0, 0, 0, 0]
[1 1 1 0 0 0 0 0 0 

[0, 1, 0, 0, 1, 0, 1, 1, 0, 0]
[0 1 0 0 1 0 1 1 0 0]
Multi-Label-Fashion-MNIST-master/8763.png
[1, 0, 1, 0, 1, 1, 0, 0, 0, 0]
[1 0 1 0 1 1 0 0 0 0]
Multi-Label-Fashion-MNIST-master/8764.png
[1, 0, 1, 0, 1, 0, 0, 0, 0, 1]
[1 0 1 0 1 0 0 0 0 1]
Multi-Label-Fashion-MNIST-master/8765.png
[0, 0, 0, 1, 0, 0, 0, 1, 0, 1]
[0 0 0 1 0 0 0 1 0 1]
Multi-Label-Fashion-MNIST-master/8766.png
[0, 1, 0, 0, 0, 0, 0, 1, 0, 0]
[0 1 0 0 0 0 0 1 0 0]
Multi-Label-Fashion-MNIST-master/8767.png
[0, 1, 0, 0, 1, 1, 0, 0, 0, 0]
[0 1 0 0 1 1 0 0 0 0]
Multi-Label-Fashion-MNIST-master/8768.png
[1, 0, 1, 0, 0, 0, 0, 0, 1, 0]
[1 0 1 0 0 0 0 0 1 0]
Multi-Label-Fashion-MNIST-master/8769.png
[0, 0, 0, 0, 0, 1, 0, 0, 1, 1]
[0 0 0 0 0 1 0 0 1 1]
Multi-Label-Fashion-MNIST-master/8770.png
[1, 0, 1, 0, 1, 0, 0, 0, 0, 0]
[1 0 1 0 1 0 0 0 0 0]
Multi-Label-Fashion-MNIST-master/8771.png
[1, 0, 0, 0, 0, 0, 1, 0, 1, 0]
[1 0 0 0 0 0 1 0 1 0]
Multi-Label-Fashion-MNIST-master/8772.png
[0, 0, 0, 0, 0, 1, 1, 0, 0, 1]
[0 0 0 0 0 1 1 0 0 

[0, 1, 1, 0, 1, 0, 0, 0, 1, 0]
[0 1 1 0 1 0 0 0 1 0]
Multi-Label-Fashion-MNIST-master/8926.png
[0, 0, 1, 0, 0, 0, 1, 0, 0, 1]
[0 0 1 0 0 0 1 0 0 1]
Multi-Label-Fashion-MNIST-master/8927.png
[0, 0, 0, 1, 1, 0, 1, 1, 0, 0]
[0 0 0 1 1 0 1 1 0 0]
Multi-Label-Fashion-MNIST-master/8928.png
[0, 0, 0, 0, 0, 1, 1, 1, 0, 0]
[0 0 0 0 0 1 1 1 0 0]
Multi-Label-Fashion-MNIST-master/8929.png
[0, 1, 1, 1, 1, 0, 0, 0, 0, 0]
[0 1 1 1 1 0 0 0 0 0]
Multi-Label-Fashion-MNIST-master/8930.png
[1, 1, 0, 0, 1, 0, 0, 0, 1, 0]
[1 1 0 0 1 0 0 0 1 0]
Multi-Label-Fashion-MNIST-master/8931.png
[1, 1, 1, 0, 0, 0, 1, 0, 0, 0]
[1 1 1 0 0 0 1 0 0 0]
Multi-Label-Fashion-MNIST-master/8932.png
[1, 0, 0, 1, 1, 0, 0, 0, 0, 0]
[1 0 0 1 1 0 0 0 0 0]
Multi-Label-Fashion-MNIST-master/8933.png
[0, 1, 1, 0, 0, 0, 0, 0, 1, 1]
[0 1 1 0 0 0 0 0 1 1]
Multi-Label-Fashion-MNIST-master/8934.png
[1, 1, 0, 0, 0, 0, 0, 1, 1, 0]
[1 1 0 0 0 0 0 1 1 0]
Multi-Label-Fashion-MNIST-master/8935.png
[1, 1, 0, 0, 0, 1, 0, 0, 0, 0]
[1 1 0 0 0 1 0 0 0 

[0, 0, 1, 0, 0, 0, 1, 0, 0, 1]
[0 0 1 0 0 0 1 0 0 1]
Multi-Label-Fashion-MNIST-master/9090.png
[0, 1, 0, 0, 1, 0, 1, 0, 0, 1]
[0 1 0 0 1 0 1 0 0 1]
Multi-Label-Fashion-MNIST-master/9091.png
[0, 0, 0, 0, 1, 1, 0, 0, 0, 1]
[0 0 0 0 1 1 0 0 0 1]
Multi-Label-Fashion-MNIST-master/9092.png
[0, 0, 0, 1, 0, 1, 0, 0, 1, 1]
[0 0 0 1 0 1 0 0 1 1]
Multi-Label-Fashion-MNIST-master/9093.png
[0, 1, 0, 1, 0, 0, 0, 1, 0, 0]
[0 1 0 1 0 0 0 1 0 0]
Multi-Label-Fashion-MNIST-master/9094.png
[1, 0, 0, 0, 0, 0, 0, 1, 1, 1]
[1 0 0 0 0 0 0 1 1 1]
Multi-Label-Fashion-MNIST-master/9095.png
[1, 1, 0, 0, 0, 0, 0, 0, 1, 0]
[1 1 0 0 0 0 0 0 1 0]
Multi-Label-Fashion-MNIST-master/9096.png
[0, 0, 0, 0, 1, 1, 1, 0, 0, 0]
[0 0 0 0 1 1 1 0 0 0]
Multi-Label-Fashion-MNIST-master/9097.png
[1, 0, 0, 0, 0, 0, 0, 1, 1, 0]
[1 0 0 0 0 0 0 1 1 0]
Multi-Label-Fashion-MNIST-master/9098.png
[1, 0, 0, 0, 1, 0, 0, 1, 0, 1]
[1 0 0 0 1 0 0 1 0 1]
Multi-Label-Fashion-MNIST-master/9099.png
[1, 0, 1, 0, 0, 1, 0, 0, 0, 0]
[1 0 1 0 0 1 0 0 0 

[1, 1, 0, 0, 0, 1, 0, 1, 0, 0]
[1 1 0 0 0 1 0 1 0 0]
Multi-Label-Fashion-MNIST-master/9253.png
[1, 0, 1, 0, 0, 0, 0, 1, 0, 0]
[1 0 1 0 0 0 0 1 0 0]
Multi-Label-Fashion-MNIST-master/9254.png
[1, 1, 0, 0, 0, 0, 0, 0, 0, 1]
[1 1 0 0 0 0 0 0 0 1]
Multi-Label-Fashion-MNIST-master/9255.png
[0, 0, 0, 0, 1, 0, 0, 1, 1, 1]
[0 0 0 0 1 0 0 1 1 1]
Multi-Label-Fashion-MNIST-master/9256.png
[1, 0, 0, 0, 0, 1, 0, 1, 1, 0]
[1 0 0 0 0 1 0 1 1 0]
Multi-Label-Fashion-MNIST-master/9257.png
[0, 1, 0, 0, 0, 1, 0, 1, 0, 1]
[0 1 0 0 0 1 0 1 0 1]
Multi-Label-Fashion-MNIST-master/9258.png
[1, 0, 0, 0, 1, 0, 1, 0, 0, 0]
[1 0 0 0 1 0 1 0 0 0]
Multi-Label-Fashion-MNIST-master/9259.png
[0, 1, 1, 0, 0, 1, 0, 0, 0, 1]
[0 1 1 0 0 1 0 0 0 1]
Multi-Label-Fashion-MNIST-master/9260.png
[0, 0, 0, 1, 1, 0, 0, 0, 0, 0]
[0 0 0 1 1 0 0 0 0 0]
Multi-Label-Fashion-MNIST-master/9261.png
[0, 0, 0, 0, 0, 0, 1, 1, 1, 1]
[0 0 0 0 0 0 1 1 1 1]
Multi-Label-Fashion-MNIST-master/9262.png
[0, 1, 0, 0, 0, 1, 0, 1, 0, 0]
[0 1 0 0 0 1 0 1 0 

[0, 1, 0, 1, 0, 0, 0, 0, 0, 1]
[0 1 0 1 0 0 0 0 0 1]
Multi-Label-Fashion-MNIST-master/9414.png
[0, 0, 0, 0, 1, 1, 0, 0, 0, 1]
[0 0 0 0 1 1 0 0 0 1]
Multi-Label-Fashion-MNIST-master/9415.png
[0, 1, 0, 0, 1, 1, 0, 0, 0, 0]
[0 1 0 0 1 1 0 0 0 0]
Multi-Label-Fashion-MNIST-master/9416.png
[1, 0, 1, 0, 0, 0, 0, 0, 1, 0]
[1 0 1 0 0 0 0 0 1 0]
Multi-Label-Fashion-MNIST-master/9417.png
[0, 1, 1, 1, 0, 0, 0, 1, 0, 0]
[0 1 1 1 0 0 0 1 0 0]
Multi-Label-Fashion-MNIST-master/9418.png
[0, 1, 0, 0, 0, 1, 1, 0, 0, 0]
[0 1 0 0 0 1 1 0 0 0]
Multi-Label-Fashion-MNIST-master/9419.png
[0, 1, 0, 1, 0, 0, 1, 0, 0, 0]
[0 1 0 1 0 0 1 0 0 0]
Multi-Label-Fashion-MNIST-master/9420.png
[0, 1, 0, 0, 0, 1, 0, 1, 0, 0]
[0 1 0 0 0 1 0 1 0 0]
Multi-Label-Fashion-MNIST-master/9421.png
[1, 0, 0, 0, 1, 0, 0, 0, 1, 0]
[1 0 0 0 1 0 0 0 1 0]
Multi-Label-Fashion-MNIST-master/9422.png
[0, 0, 0, 0, 0, 1, 1, 1, 1, 0]
[0 0 0 0 0 1 1 1 1 0]
Multi-Label-Fashion-MNIST-master/9423.png
[0, 0, 0, 0, 0, 0, 1, 1, 1, 1]
[0 0 0 0 0 0 1 1 1 

[1, 0, 0, 0, 0, 1, 0, 1, 0, 0]
[1 0 0 0 0 1 0 1 0 0]
Multi-Label-Fashion-MNIST-master/9578.png
[1, 1, 1, 0, 0, 0, 0, 0, 0, 1]
[1 1 1 0 0 0 0 0 0 1]
Multi-Label-Fashion-MNIST-master/9579.png
[0, 0, 0, 0, 0, 1, 1, 0, 0, 1]
[0 0 0 0 0 1 1 0 0 1]
Multi-Label-Fashion-MNIST-master/9580.png
[1, 0, 1, 0, 1, 0, 1, 0, 0, 0]
[1 0 1 0 1 0 1 0 0 0]
Multi-Label-Fashion-MNIST-master/9581.png
[0, 1, 0, 0, 0, 1, 1, 0, 0, 0]
[0 1 0 0 0 1 1 0 0 0]
Multi-Label-Fashion-MNIST-master/9582.png
[1, 0, 0, 0, 1, 0, 1, 1, 0, 0]
[1 0 0 0 1 0 1 1 0 0]
Multi-Label-Fashion-MNIST-master/9583.png
[1, 1, 0, 0, 0, 0, 0, 0, 0, 1]
[1 1 0 0 0 0 0 0 0 1]
Multi-Label-Fashion-MNIST-master/9584.png
[0, 1, 0, 0, 0, 1, 0, 0, 1, 1]
[0 1 0 0 0 1 0 0 1 1]
Multi-Label-Fashion-MNIST-master/9585.png
[0, 0, 0, 1, 1, 0, 1, 1, 0, 0]
[0 0 0 1 1 0 1 1 0 0]
Multi-Label-Fashion-MNIST-master/9586.png
[0, 0, 0, 0, 0, 0, 1, 1, 1, 0]
[0 0 0 0 0 0 1 1 1 0]
Multi-Label-Fashion-MNIST-master/9587.png
[1, 1, 0, 1, 0, 0, 0, 1, 0, 0]
[1 1 0 1 0 0 0 1 0 

[0, 1, 0, 0, 0, 0, 1, 1, 0, 1]
[0 1 0 0 0 0 1 1 0 1]
Multi-Label-Fashion-MNIST-master/9742.png
[1, 1, 1, 0, 0, 0, 0, 0, 0, 0]
[1 1 1 0 0 0 0 0 0 0]
Multi-Label-Fashion-MNIST-master/9743.png
[1, 0, 1, 0, 0, 0, 0, 1, 1, 0]
[1 0 1 0 0 0 0 1 1 0]
Multi-Label-Fashion-MNIST-master/9744.png
[1, 0, 1, 0, 0, 0, 0, 1, 0, 0]
[1 0 1 0 0 0 0 1 0 0]
Multi-Label-Fashion-MNIST-master/9745.png
[1, 0, 0, 1, 0, 0, 0, 1, 0, 0]
[1 0 0 1 0 0 0 1 0 0]
Multi-Label-Fashion-MNIST-master/9746.png
[0, 0, 1, 0, 0, 0, 0, 0, 1, 1]
[0 0 1 0 0 0 0 0 1 1]
Multi-Label-Fashion-MNIST-master/9747.png
[1, 0, 0, 0, 1, 0, 1, 0, 0, 1]
[1 0 0 0 1 0 1 0 0 1]
Multi-Label-Fashion-MNIST-master/9748.png
[1, 0, 0, 0, 1, 0, 1, 0, 1, 0]
[1 0 0 0 1 0 1 0 1 0]
Multi-Label-Fashion-MNIST-master/9749.png
[1, 1, 0, 0, 0, 0, 0, 1, 0, 0]
[1 1 0 0 0 0 0 1 0 0]
Multi-Label-Fashion-MNIST-master/9750.png
[1, 0, 0, 1, 0, 1, 0, 0, 0, 1]
[1 0 0 1 0 1 0 0 0 1]
Multi-Label-Fashion-MNIST-master/9751.png
[0, 0, 1, 1, 0, 0, 0, 1, 0, 0]
[0 0 1 1 0 0 0 1 0 

[0, 0, 1, 0, 0, 0, 0, 1, 1, 0]
[0 0 1 0 0 0 0 1 1 0]
Multi-Label-Fashion-MNIST-master/9905.png
[0, 1, 0, 0, 0, 1, 0, 1, 0, 1]
[0 1 0 0 0 1 0 1 0 1]
Multi-Label-Fashion-MNIST-master/9906.png
[1, 0, 0, 1, 1, 0, 1, 0, 0, 0]
[1 0 0 1 1 0 1 0 0 0]
Multi-Label-Fashion-MNIST-master/9907.png
[0, 1, 1, 0, 1, 0, 0, 0, 0, 1]
[0 1 1 0 1 0 0 0 0 1]
Multi-Label-Fashion-MNIST-master/9908.png
[0, 0, 0, 0, 1, 0, 1, 0, 1, 1]
[0 0 0 0 1 0 1 0 1 1]
Multi-Label-Fashion-MNIST-master/9909.png
[0, 1, 0, 0, 1, 0, 0, 0, 0, 1]
[0 1 0 0 1 0 0 0 0 1]
Multi-Label-Fashion-MNIST-master/9910.png
[0, 1, 1, 0, 0, 1, 0, 1, 0, 0]
[0 1 1 0 0 1 0 1 0 0]
Multi-Label-Fashion-MNIST-master/9911.png
[0, 0, 0, 0, 1, 1, 1, 0, 0, 0]
[0 0 0 0 1 1 1 0 0 0]
Multi-Label-Fashion-MNIST-master/9912.png
[0, 0, 0, 0, 1, 0, 1, 0, 1, 0]
[0 0 0 0 1 0 1 0 1 0]
Multi-Label-Fashion-MNIST-master/9913.png
[1, 0, 1, 0, 1, 0, 0, 0, 0, 1]
[1 0 1 0 1 0 0 0 0 1]
Multi-Label-Fashion-MNIST-master/9914.png
[1, 1, 0, 0, 0, 0, 0, 0, 0, 0]
[1 1 0 0 0 0 0 0 0 

In [7]:
X = np.array(raw_pic)
print(" >>> train_img.shape = ", X.shape)
train_img_size_h = X.shape[1]
train_img_size_w = X.shape[2]
print(" >>> h = ", train_img_size_h)
print(" >>> w = ", train_img_size_w)

# train_img = train_img.astype('float32') 
X = X/255

#--- preprocess label ----------------------------------------------------------
Y = np.array(raw_lbl)
print(" >>> train_ans.shape = ", Y.shape)


 >>> train_img.shape =  (10000, 104, 357, 3)
 >>> h =  104
 >>> w =  357
 >>> train_ans.shape =  (10000, 10)


In [8]:
from sklearn import model_selection
print('\nPreparing Classifier Training and Validation Data...')
X_train, X_test, y_train, y_test = model_selection.train_test_split(X,Y,test_size=0.1)


Preparing Classifier Training and Validation Data...


In [12]:
input_shape_img = (X_train.shape[1], X_train.shape[2], 3)
batch_size = 32
num_epochs = 15
num_classes = 10
conv_size = 32

print(" >>> input_shape_img = ", input_shape_img)

#-------------------------------------------------------------------------------
model = Sequential()

model.add(Conv2D(conv_size, (3, 3), activation='relu', padding='same', input_shape=input_shape_img)) 
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(conv_size, (3, 3), activation='relu', padding='same'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(conv_size, (3, 3), activation='relu', padding='same'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(conv_size, (3, 3), activation='relu', padding='same')) 
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(conv_size, (3, 3), activation='relu', padding='same')) 
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(GlobalAveragePooling2D())

model.add(Dense(num_classes, activation='sigmoid'))

model.compile(loss='binary_crossentropy',
                        optimizer='adam',
                        metrics=['accuracy'])
              
model.summary()

 >>> input_shape_img =  (104, 357, 3)
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_6 (Conv2D)            (None, 104, 357, 32)      896       
_________________________________________________________________
max_pooling2d_6 (MaxPooling2 (None, 52, 178, 32)       0         
_________________________________________________________________
conv2d_7 (Conv2D)            (None, 52, 178, 32)       9248      
_________________________________________________________________
max_pooling2d_7 (MaxPooling2 (None, 26, 89, 32)        0         
_________________________________________________________________
conv2d_8 (Conv2D)            (None, 26, 89, 32)        9248      
_________________________________________________________________
max_pooling2d_8 (MaxPooling2 (None, 13, 44, 32)        0         
_________________________________________________________________
conv2d_9 (Conv2D)            (None, 13

In [13]:
from keras.callbacks import EarlyStopping
early_stop = EarlyStopping(monitor='loss', patience=5, verbose=1)
                                            
history = model.fit(X_train, y_train,
                        batch_size=batch_size,
                        epochs=num_epochs,
                        verbose=1,
                        validation_split=0.1,
                        callbacks=[early_stop])

Train on 8100 samples, validate on 900 samples
Epoch 1/15
8100/8100 [==============================] - 160s 20ms/step - loss: 0.6267 - acc: 0.6639 - val_loss: 0.5579 - val_acc: 0.7111
Epoch 2/15
8100/8100 [==============================] - 153s 19ms/step - loss: 0.4801 - acc: 0.7613 - val_loss: 0.4213 - val_acc: 0.8011
Epoch 3/15
8100/8100 [==============================] - 150s 19ms/step - loss: 0.3828 - acc: 0.8230 - val_loss: 0.3687 - val_acc: 0.8291
Epoch 4/15
8100/8100 [==============================] - 143s 18ms/step - loss: 0.3322 - acc: 0.8520 - val_loss: 0.3576 - val_acc: 0.8366
Epoch 5/15
8100/8100 [==============================] - 158s 20ms/step - loss: 0.2958 - acc: 0.8710 - val_loss: 0.3009 - val_acc: 0.8669
Epoch 6/15
8100/8100 [==============================] - 170s 21ms/step - loss: 0.2669 - acc: 0.8847 - val_loss: 0.2737 - val_acc: 0.8824
Epoch 7/15
8100/8100 [==============================] - 150s 19ms/step - loss: 0.2470 - acc: 0.8946 - val_loss: 0.2783 - val_acc: 0

In [15]:
acc = model.evaluate(X_test, y_test, verbose=1)[1]
print(" >>> acc = ", acc)

1000/1000 [==============================] - 9s 9ms/step
 >>> acc =  0.9291000261306762


In [16]:
from keras.models import load_model

# Creates a HDF5 file 'my_model.h5'
model.save('outfit_model.h5')
